/* sccsdata.c - sccs data file for mtrprog generated by mksccs */

char mtrprog_sccsdata_c_sccsid[] = "@(#)sccsdata.c	1.31 18/9/92";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  ifdefs.h: Don't use SYSTYPE_BSD43 to set OS_NEWSOS as RISC/os sets this
 *  	  as well.  We now depend on -Driscos in the top level ups
 *  	  Makefile.
 */

 const char *_mtrprog_sccsdata[] = {
	"mtrprog version 1.31 (build date: Fri Sep 18 17:27:00 BST 1992)",
	"@{$mtrprog$}: sccsdata.c 1.31 ",
	"@{$mtrprog$}: e_close.c 1.7 ",
	"@{$mtrprog$}: is_number.c 1.4 ",
	"@{$mtrprog$}: memxxx.c 1.6 ",
	"@{$mtrprog$}: query_user.c 1.6 ",
	"@{$mtrprog$}: rm_rf.c 1.8 ",
	"@{$mtrprog$}: serverhost.c 1.6 ",
	"@{$mtrprog$}: so.c 1.22 ",
	"@{$mtrprog$}: strcache.c 1.18 ",
	"@{$mtrprog$}: regex.c 1.7 ",
	"@{$mtrprog$}: strtod.c 1.11 ",
	"@{$mtrprog$}: swap_longs.c 1.4 ",
	"@{$mtrprog$}: appltofl.c 1.8 ",
	"@{$mtrprog$}: fmtostr.c 1.4 ",
	"@{$mtrprog$}: fttostr.c 1.4 ",
	"@{$mtrprog$}: fopnew.c 1.5 ",
	"@{$mtrprog$}: strtobsz.c 1.6 ",
	"@{$mtrprog$}: mtrprog_vers.c 1.5 ",
	"@{$mtrprog$}: alloc.h 1.7 ",
	"@{$mtrprog$}: genmergesort.h 1.6 ",
	"@{$mtrprog$}: ifdefs.h 1.12 ",
	"@{$mtrprog$}: regex.h 1.2 ",
	"@{$mtrprog$}: sccsdata.h 1.2 ",
	"@{$mtrprog$}: serverhost.h 1.2 ",
	"@{$mtrprog$}: so.h 1.10 ",
	"@{$mtrprog$}: strcache.h 1.6 ",
	"@{$mtrprog$}: utils.h 1.13 ",
	"@{$mtrprog$}: Makefile 1.29 ",
};
