.\"Man page for seahaven, by Terry Weissman.
.TH seahaven 6 "07 Feb 1991"
.SH NAME
\fISeahaven Towers\fR - A solitaire game
.SH SYNOPSIS
.B seahaven
[-display display:number] [-speedup num]
.SH DESCRIPTION
.I seahaven
is an X implementation of a solitaire game sometimes known as 
.I Seahaven Towers,
which I originally saw as a shareware game for the Macintosh.  
.I seahaven
is a fairly blatent rip-off of that game.

.SH RULES FOR SEAHAVEN TOWERS

The game is played using an ordinary deck of cards.  The cards are all
face-up; you always know where all of the cards are.  At any time,
each card is in one of three kinds of stacks:

- Playing stacks.  There are ten of these, each initially having five
cards.

- Working stacks.  There are four of these, two of them initially
having a card in them.  Each working stack is allowed to contain at
most one card.

- Ace stacks.  There are four of these, one for each suit.  They are
initially empty.  Cards must be placed in these stacks in ascending
order, starting with the ace.  The object of the game is to get all
the cards in the ace stacks.

The rules are simple.  You may only move one card at a time; only a
card in a working stack or on the top of a playing stack may be moved.
A card may be moved to the top of a playing stack only if it is the
same suit that was on top there and the next lower card.  (In other
words, you may only place the seven of spades on top of the eight of
spades.)  A card may be moved to any empty working stack.  And a card
may be moved to an ace stack if it is an ace or if it is the next
higher card than the one that is already there.


.SH PLAYING SEAHAVEN

To move a card, just drag it with the left mouse button.  When you let
go, it will be placed on the stack that the card was moved closest to,
if such a move is legal.  If the move is not legal, the card will
spring back to its original location.

Since it is always to your advantage to move cards to the ace stacks
as soon as possible, cards will be automatically moved there for you.

There is also a convenient shortcut: you may move several cards at
once from one playing stack to another, providing that such a move
would be possible using available empty work stacks.

To help you locate cards, if you press the middle button on a card,
the next lower card of the same suit will be highlighted.  If you
press the right button, the next higher card will be highlighted.

Since there is no hidden information in the game, it's not quite
cheating to provide undo commands.  There are Undo and Redo buttons at
the bottom of the window; you may also use the U and R keys.  The
Restart button will restore you back to the original set-up.

If you give up, you can press the Autoplay button.  This counts as a
loss (unless you've already won the hand).  The computer will figure
out whether there's a solution.  If there is, you can review the
computer's solution by using the Restart and Redo buttons.

.SH SCORING

If you get all the cards into the ace piles, you will be scored a win.
If you press the New Game button or the Autoplay button without having
won, you will be scored a loss.  Your wins and losses will be
remembered across invocations of 
.I seahaven.

.SH COMMAND LINE OPTIONS

The -speedup flag changes the speed of the animation.  The higher the
number, the faster cards will move when automatically transferred to
the ace piles.  The default value is 6.

.SH BUGS

Needs an icon.

Does not look at any resources at all.  That is, your .Xdefaults file
will be ignored.

Lots of the code is horrid.

This man page is poorly written.


.SH COPYRIGHT


Copyright 1991 by Terry Weissman and Charles Haynes.

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation, and that the names of	Terry Weissman or
Charles Haynes or their employers not be used in advertising or
publicity pertaining to distribution of the software without specific,
written prior permission.  Terry Weissman and Charles Haynes make no
representations about the suitability of this software for any
purpose.  It is provided "as is" without express or implied warranty.

TERRY WEISSMAN AND CHARLES HAYNES AND THEIR EMPLOYERS DISCLAIM ALL
WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL THEY BE
LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

So there.


.SH AUTHORS


Terry Weissman
.br
Silicon Graphics, Incorporated
.br
weissman@sgi.com

Auto-play code by

Charles Haynes
.br
Western Software Laboratory
.br
Digital Equipment Corporation
.br
haynes@wsl.dec.com
