/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /a/cvs/386BSD/ports/db/ingres/src/sql/scn2.c,v 1.2 1994/06/19 05:38:31 alm Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int yywrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	/* Whether we've seen an EOF on this buffer. */
	int yy_eof_status;
#define EOF_NOT_SEEN 0
	/* "Pending" happens when the EOF has been seen but there's still
	 * some text to process.  Note that when we actually see the EOF,
	 * we switch the status back to "not seen" (via yyrestart()), so
	 * that the user can continue scanning by just pointing yyin at
	 * a new input file.
	 */
#define EOF_PENDING 1
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
static void yy_push_state YY_PROTO(( int new_state ));
static void yy_pop_state YY_PROTO(( void ));
static int yy_top_state YY_PROTO(( void ));

#ifndef yytext_ptr
static void yy_flex_strcpy YY_PROTO(( char *, const char * ));
#endif

static void *yy_flex_alloc YY_PROTO(( unsigned int ));
static void *yy_flex_realloc YY_PROTO(( void *ptr, unsigned int ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
#define SQL 1
typedef unsigned char YY_CHAR;
typedef int yy_state_type;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
extern char *yytext;
#define yytext_ptr yytext

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yytext_ptr -= yy_more_len; \
	yyleng = yy_cp - yytext_ptr; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 109
static const short int yy_accept[409] =
    {   0,
        0,    0,    0,    0,  109,  107,  104,  107,  105,  103,
      107,   92,   92,   92,   95,  107,   88,   86,   89,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,    0,  105,    0,  102,  101,  106,   97,    0,   96,
       95,    0,   94,   90,   87,   91,   93,   93,   93,   10,
       93,   93,   93,   14,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   42,   47,   93,   93,   93,   93,   93,   93,   93,
       54,   55,   93,   58,   93,   93,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   75,   93,   93,   93,   93,
       93,   93,   93,   93,    0,  106,    0,  100,   96,    0,
        0,   98,   94,    2,    3,    9,   11,   93,    4,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   34,
       93,   93,    0,   93,   93,   93,   93,   93,   93,   45,
       48,   93,   93,    6,    5,   51,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       70,   93,   93,   93,    7,   93,   93,   93,   93,   93,
       93,   93,   93,   93,    0,    0,   99,   93,   93,   15,

       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   27,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   37,    0,   38,   93,   93,   93,   93,   93,
       93,   46,   93,   50,   52,   93,   56,   93,   93,   93,
       93,   93,   93,   93,   65,   93,   93,   93,   93,   93,
       72,   93,   93,   93,   93,   93,   79,   93,   81,   93,
       93,   84,   85,    0,   93,   93,   93,   16,   17,   93,
       93,    8,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   32,   33,   93,   36,   38,   39,   40,
       93,   93,   93,   93,   93,   93,   93,   59,   93,   93,

       93,   93,   93,   93,   93,   93,   93,   93,   93,   74,
       76,   93,   93,   93,   93,   83,    0,   93,   93,   93,
       18,   93,   20,   93,   22,   93,   93,   93,   26,   93,
       29,   30,   31,   93,   41,   93,   44,   93,   93,   93,
       57,   93,   93,   93,   93,   64,   93,   93,   68,   69,
       93,   93,   77,   78,   80,   93,    0,   93,   13,   93,
       93,   21,   23,   24,   25,   93,   35,   93,   45,   93,
       53,   93,   61,   93,   93,   93,   93,   93,   73,   93,
        1,   93,   93,   19,   28,   93,   49,   93,   93,   93,
       93,   67,   71,   82,   93,   15,   43,   60,   93,   63,

       93,   93,   62,   66,   93,   93,   12,    0
    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    5,    6,
        6,    6,    7,    6,    8,    9,    6,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    6,   12,
       13,   14,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
        1,    1,    1,    1,   41,    1,   24,   24,   24,   24,

       42,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[43] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        3,    4
    } ;

static const short int yy_base[415] =
    {   0,
        0,    1,   20,    0,  456,  457,  457,  417,    3,  457,
        3,  457,  446,   53,   55,    0,    0,  457,  440,   40,
       48,   56,   60,   48,   73,   48,  437,   65,    0,  432,
       81,   85,   55,   81,   71,   88,   93,  100,   86,  103,
      108,  431,    7,    7,  457,  457,    0,  113,    8,  115,
      126,  131,    0,  457,  457,  457,    0,  423,  103,  431,
      413,  425,  411,    0,  125,  415,  119,  424,  410,  132,
      408,  405,  422,  137,  404,  408,  116,  407,  125,  135,
      399,  143,    0,  395,  405,  407,  393,  402,  395,   43,
        0,    0,  144,  410,  143,  411,  154,  400,  403,  141,

      409,  396,  396,  394,  404,    0,  396,  400,  398,  390,
      396,  395,  379,  380,  394,    0,  400,  399,  160,  173,
      398,  397,    0,    0,    0,    0,    0,  384,    0,  368,
      372,  386,  369,  374,  366,  371,  383,  152,  163,  382,
      377,  378,  360,  377,  377,  374,  357,  372,  373,  368,
      358,  358,  169,  355,  355,  347,  358,  357,  360,  114,
        0,  357,  358,    0,    0,    0,  350,  356,  346,  350,
      353,  354,  146,  353,  343,  342,  348,  340,  346,  345,
        0,  337,  343,  344,    0,  334,  159,  344,  326,  322,
      319,  159,  333,  329,  351,  342,  341,  321,  330,  333,

      322,  327,  322,  321,  309,  308,  322,  311,  312,  323,
      302,  302,    0,  312,  308,  303,  330,  297,  308,  295,
      305,  309,    0,  297,    0,  291,  294,  295,  305,  289,
      299,    0,  284,    0,    0,  286,    0,  288,  284,  292,
      299,  290,  293,  288,    0,  278,  293,  281,  290,  280,
        0,  276,  285,  275,  267,  267,    0,  281,    0,  280,
      279,    0,    0,  190,  265,  277,  278,    0,    0,  260,
      265,    0,  273,  263,  258,  274,  256,  261,  267,  257,
      265,  264,  249,    0,    0,  260,    0,  457,    0,    0,
      259,  264,  244,  258,  261,  252,  246,    0,  240,  240,

      245,  252,  252,  249,  252,  251,  231,  241,  245,    0,
        0,  243,  242,  227,  223,    0,  227,  234,  228,  221,
        0,  219,    0,  219,    0,  226,  232,  216,    0,  232,
        0,    0,    0,  220,    0,  213,    0,  214,  224,  227,
        0,  220,  203,  222,  205,    0,  207,  205,    0,    0,
      193,  201,    0,    0,    0,  200,  192,  177,    0,  197,
      196,    0,    0,    0,    0,  180,    0,  184,    0,  193,
        0,  182,    0,  189,  177,  191,  182,  172,    0,  173,
      457,  189,  169,    0,    0,  168,    0,  171,  179,  178,
      177,    0,    0,    0,  161,    0,    0,    0,  161,    0,

      160,  130,    0,    0,   65,   43,    0,  457,  223,  227,
       13,  229,  233,  235
    } ;

static const short int yy_def[415] =
    {   0,
      409,  409,  408,    3,  408,  408,  408,  408,  408,  408,
      410,  408,  408,  408,  408,  411,  408,  408,  408,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  408,  408,  410,  408,  408,  413,  408,  408,  408,
      408,  408,  414,  408,  408,  408,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  408,  413,  408,  408,  408,  408,
      408,  408,  414,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  408,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  408,  408,  408,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  408,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  408,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  408,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  408,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  408,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      408,  412,  412,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  412,  412,  412,  412,  412,  412,  412,  412,

      412,  412,  412,  412,  412,  412,  412,    0,  408,  408,
      408,  408,  408,  408
    } ;

static const short int yy_nxt[500] =
    {   0,
      408,  408,    7,    7,   43,   45,   43,   46,   43,   45,
       43,   46,   54,   55,  117,  117,   53,  118,    8,    8,
        6,    9,   10,    9,   11,   12,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       29,   36,   37,   38,   39,   40,   41,   29,   29,   29,
        6,   29,   48,   50,   51,   58,   63,   59,  167,  168,
      407,   49,   60,   52,   61,   62,   79,   65,   70,   80,
       73,   66,   71,   89,   67,   74,   64,   68,   72,   90,
       69,   75,   82,  406,   49,   85,   52,   83,   76,   87,

       91,   77,   95,   86,   78,   96,   97,   88,   92,   99,
       93,  100,   94,  107,  105,  108,   98,  110,  109,  101,
      125,  102,   48,  103,  119,  111,  153,  104,  106,  112,
      113,   49,  231,  120,   50,   51,  114,  121,  121,  131,
      122,  126,  232,  132,   52,  134,  135,  150,  139,  155,
      151,  140,  405,  136,   49,  146,  120,  141,  154,  147,
      158,  172,  169,  156,  142,  173,  180,   52,  176,  119,
      153,  174,  241,  177,  181,  159,  160,  170,  120,  196,
      196,  242,  197,  207,  208,  209,  260,  254,  210,  255,
      261,  264,  404,  403,  402,  401,  400,  399,  398,  397,

      396,  120,  224,  395,  394,  393,  392,  391,  390,  389,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,  317,    6,    6,    6,    6,   44,   44,   44,
       44,   57,   57,  116,  376,  116,  116,  123,  123,  375,
      374,  373,  372,  371,  370,  369,  368,  367,  366,  365,
      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  316,  315,  314,

      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,
      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  264,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      197,  197,  264,  263,  262,  259,  258,  257,  256,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      240,  239,  238,  237,  236,  235,  234,  233,  230,  229,
      228,  227,  226,  225,  223,  222,  221,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  206,  205,  204,

      203,  202,  201,  200,  199,  198,  122,  122,  118,  118,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  179,  178,  175,  171,  166,  165,
      164,  163,  162,  161,  157,  152,  149,  148,  145,  144,
      143,  138,  137,  133,  130,  129,  128,  127,  124,  115,
       84,   81,   56,   47,   42,  408,    5,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408

    } ;

static const short int yy_chk[500] =
    {   0,
        0,    0,    1,    2,    9,   11,    9,   11,   43,   44,
       43,   44,   17,   17,   49,   49,  411,   49,    1,    2,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,   14,   15,   15,   20,   21,   20,   90,   90,
      406,   14,   20,   15,   20,   20,   26,   22,   23,   26,
       24,   22,   23,   33,   22,   24,   21,   22,   23,   33,
       22,   25,   28,  405,   14,   31,   15,   28,   25,   32,

       34,   25,   35,   31,   25,   35,   36,   32,   34,   37,
       34,   37,   34,   39,   38,   39,   36,   40,   39,   37,
       59,   37,   48,   37,   50,   40,   79,   37,   38,   41,
       41,   48,  160,   50,   51,   51,   41,   52,   52,   65,
       52,   59,  160,   65,   51,   67,   67,   77,   70,   80,
       77,   70,  402,   67,   48,   74,   50,   70,   79,   74,
       82,   95,   93,   80,   70,   95,  100,   51,   97,  119,
      153,   95,  173,   97,  100,   82,   82,   93,  119,  120,
      120,  173,  120,  138,  138,  139,  192,  187,  139,  187,
      192,  264,  401,  399,  395,  391,  390,  389,  388,  386,

      383,  119,  153,  382,  380,  378,  377,  376,  375,  374,
      372,  370,  368,  366,  361,  360,  358,  357,  356,  352,
      351,  348,  264,  409,  409,  409,  409,  410,  410,  410,
      410,  412,  412,  413,  347,  413,  413,  414,  414,  345,
      344,  343,  342,  340,  339,  338,  336,  334,  330,  328,
      327,  326,  324,  322,  320,  319,  318,  317,  315,  314,
      313,  312,  309,  308,  307,  306,  305,  304,  303,  302,
      301,  300,  299,  297,  296,  295,  294,  293,  292,  291,
      286,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  271,  270,  267,  266,  265,  261,  260,  258,

      256,  255,  254,  253,  252,  250,  249,  248,  247,  246,
      244,  243,  242,  241,  240,  239,  238,  236,  233,  231,
      230,  229,  228,  227,  226,  224,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  191,  190,  189,  188,  186,
      184,  183,  182,  180,  179,  178,  177,  176,  175,  174,
      172,  171,  170,  169,  168,  167,  163,  162,  159,  158,
      157,  156,  155,  154,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  141,  140,  137,  136,  135,

      134,  133,  132,  131,  130,  128,  122,  121,  118,  117,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  105,
      104,  103,  102,  101,   99,   98,   96,   94,   89,   88,
       87,   86,   85,   84,   81,   78,   76,   75,   73,   72,
       71,   69,   68,   66,   63,   62,   61,   60,   58,   42,
       30,   27,   19,   13,    8,    5,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
char *yytext;
# line 1 "scn2.l"
# line 2 "scn2.l"
#include "sql2.h"

#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif

#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif

#ifdef HAVE_STRING_H
#include <string.h>
#endif

int lineno = 1;
void yyerror(char *s);

	/* macro to save the text of a SQL token */
#define SV save_str(yytext)

	/* macro to save the text and return a token */
#define TOK(name) { SV;return name; }

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

# line 26 "scn2.l"



	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = yyleng;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 409 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 457 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_USER_ACTION
# line 28 "scn2.l"
{ BEGIN SQL; start_save(); }
	YY_BREAK
	/* literal keyword tokens */
case 2:
YY_USER_ACTION
# line 33 "scn2.l"
TOK(ALL)
	YY_BREAK
case 3:
YY_USER_ACTION
# line 34 "scn2.l"
TOK(AND)
	YY_BREAK
case 4:
YY_USER_ACTION
# line 35 "scn2.l"
TOK(AMMSC)
	YY_BREAK
case 5:
YY_USER_ACTION
# line 36 "scn2.l"
TOK(AMMSC)
	YY_BREAK
case 6:
YY_USER_ACTION
# line 37 "scn2.l"
TOK(AMMSC)
	YY_BREAK
case 7:
YY_USER_ACTION
# line 38 "scn2.l"
TOK(AMMSC)
	YY_BREAK
case 8:
YY_USER_ACTION
# line 39 "scn2.l"
TOK(AMMSC)
	YY_BREAK
case 9:
YY_USER_ACTION
# line 40 "scn2.l"
TOK(ANY)
	YY_BREAK
case 10:
YY_USER_ACTION
# line 41 "scn2.l"
TOK(AS)
	YY_BREAK
case 11:
YY_USER_ACTION
# line 42 "scn2.l"
TOK(ASC)
	YY_BREAK
case 12:
YY_USER_ACTION
# line 43 "scn2.l"
TOK(AUTHORIZATION)
	YY_BREAK
case 13:
YY_USER_ACTION
# line 44 "scn2.l"
TOK(BETWEEN)
	YY_BREAK
case 14:
YY_USER_ACTION
# line 45 "scn2.l"
TOK(BY)
	YY_BREAK
case 15:
YY_USER_ACTION
# line 46 "scn2.l"
TOK(CHARACTER)
	YY_BREAK
case 16:
YY_USER_ACTION
# line 47 "scn2.l"
TOK(CHECK)
	YY_BREAK
case 17:
YY_USER_ACTION
# line 48 "scn2.l"
TOK(CLOSE)
	YY_BREAK
case 18:
YY_USER_ACTION
# line 49 "scn2.l"
TOK(COMMIT)
	YY_BREAK
case 19:
YY_USER_ACTION
# line 50 "scn2.l"
TOK(CONTINUE)
	YY_BREAK
case 20:
YY_USER_ACTION
# line 51 "scn2.l"
TOK(CREATE)
	YY_BREAK
case 21:
YY_USER_ACTION
# line 52 "scn2.l"
TOK(CURRENT)
	YY_BREAK
case 22:
YY_USER_ACTION
# line 53 "scn2.l"
TOK(CURSOR)
	YY_BREAK
case 23:
YY_USER_ACTION
# line 54 "scn2.l"
TOK(DECIMAL)
	YY_BREAK
case 24:
YY_USER_ACTION
# line 55 "scn2.l"
TOK(DECLARE)
	YY_BREAK
case 25:
YY_USER_ACTION
# line 56 "scn2.l"
TOK(DEFAULT)
	YY_BREAK
case 26:
YY_USER_ACTION
# line 57 "scn2.l"
TOK(DELETE)
	YY_BREAK
case 27:
YY_USER_ACTION
# line 58 "scn2.l"
TOK(DESC)
	YY_BREAK
case 28:
YY_USER_ACTION
# line 59 "scn2.l"
TOK(DISTINCT)
	YY_BREAK
case 29:
YY_USER_ACTION
# line 60 "scn2.l"
TOK(DOUBLE)
	YY_BREAK
case 30:
YY_USER_ACTION
# line 61 "scn2.l"
TOK(ESCAPE)
	YY_BREAK
case 31:
YY_USER_ACTION
# line 62 "scn2.l"
TOK(EXISTS)
	YY_BREAK
case 32:
YY_USER_ACTION
# line 63 "scn2.l"
TOK(FETCH)
	YY_BREAK
case 33:
YY_USER_ACTION
# line 64 "scn2.l"
TOK(FLOAT)
	YY_BREAK
case 34:
YY_USER_ACTION
# line 65 "scn2.l"
TOK(FOR)
	YY_BREAK
case 35:
YY_USER_ACTION
# line 66 "scn2.l"
TOK(FOREIGN)
	YY_BREAK
case 36:
YY_USER_ACTION
# line 67 "scn2.l"
TOK(FOUND)
	YY_BREAK
case 37:
YY_USER_ACTION
# line 68 "scn2.l"
TOK(FROM)
	YY_BREAK
case 38:
YY_USER_ACTION
# line 69 "scn2.l"
TOK(GOTO)
	YY_BREAK
case 39:
YY_USER_ACTION
# line 70 "scn2.l"
TOK(GRANT)
	YY_BREAK
case 40:
YY_USER_ACTION
# line 71 "scn2.l"
TOK(GROUP)
	YY_BREAK
case 41:
YY_USER_ACTION
# line 72 "scn2.l"
TOK(HAVING)
	YY_BREAK
case 42:
YY_USER_ACTION
# line 73 "scn2.l"
TOK(IN)
	YY_BREAK
case 43:
YY_USER_ACTION
# line 74 "scn2.l"
TOK(INDICATOR)
	YY_BREAK
case 44:
YY_USER_ACTION
# line 75 "scn2.l"
TOK(INSERT)
	YY_BREAK
case 45:
YY_USER_ACTION
# line 76 "scn2.l"
TOK(INTEGER)
	YY_BREAK
case 46:
YY_USER_ACTION
# line 77 "scn2.l"
TOK(INTO)
	YY_BREAK
case 47:
YY_USER_ACTION
# line 78 "scn2.l"
TOK(IS)
	YY_BREAK
case 48:
YY_USER_ACTION
# line 79 "scn2.l"
TOK(KEY)
	YY_BREAK
case 49:
YY_USER_ACTION
# line 80 "scn2.l"
TOK(LANGUAGE)
	YY_BREAK
case 50:
YY_USER_ACTION
# line 81 "scn2.l"
TOK(LIKE)
	YY_BREAK
case 51:
YY_USER_ACTION
# line 82 "scn2.l"
TOK(NOT)
	YY_BREAK
case 52:
YY_USER_ACTION
# line 83 "scn2.l"
TOK(NULLX)
	YY_BREAK
case 53:
YY_USER_ACTION
# line 84 "scn2.l"
TOK(NUMERIC)
	YY_BREAK
case 54:
YY_USER_ACTION
# line 85 "scn2.l"
TOK(OF)
	YY_BREAK
case 55:
YY_USER_ACTION
# line 86 "scn2.l"
TOK(ON)
	YY_BREAK
case 56:
YY_USER_ACTION
# line 87 "scn2.l"
TOK(OPEN)
	YY_BREAK
case 57:
YY_USER_ACTION
# line 88 "scn2.l"
TOK(OPTION)
	YY_BREAK
case 58:
YY_USER_ACTION
# line 89 "scn2.l"
TOK(OR)
	YY_BREAK
case 59:
YY_USER_ACTION
# line 90 "scn2.l"
TOK(ORDER)
	YY_BREAK
case 60:
YY_USER_ACTION
# line 91 "scn2.l"
TOK(PRECISION)
	YY_BREAK
case 61:
YY_USER_ACTION
# line 92 "scn2.l"
TOK(PRIMARY)
	YY_BREAK
case 62:
YY_USER_ACTION
# line 93 "scn2.l"
TOK(PRIVILEGES)
	YY_BREAK
case 63:
YY_USER_ACTION
# line 94 "scn2.l"
TOK(PROCEDURE)
	YY_BREAK
case 64:
YY_USER_ACTION
# line 95 "scn2.l"
TOK(PUBLIC)
	YY_BREAK
case 65:
YY_USER_ACTION
# line 96 "scn2.l"
TOK(REAL)
	YY_BREAK
case 66:
YY_USER_ACTION
# line 97 "scn2.l"
TOK(REFERENCES)
	YY_BREAK
case 67:
YY_USER_ACTION
# line 98 "scn2.l"
TOK(ROLLBACK)
	YY_BREAK
case 68:
YY_USER_ACTION
# line 99 "scn2.l"
TOK(SCHEMA)
	YY_BREAK
case 69:
YY_USER_ACTION
# line 100 "scn2.l"
TOK(SELECT)
	YY_BREAK
case 70:
YY_USER_ACTION
# line 101 "scn2.l"
TOK(SET)
	YY_BREAK
case 71:
YY_USER_ACTION
# line 102 "scn2.l"
TOK(SMALLINT)
	YY_BREAK
case 72:
YY_USER_ACTION
# line 103 "scn2.l"
TOK(SOME)
	YY_BREAK
case 73:
YY_USER_ACTION
# line 104 "scn2.l"
TOK(SQLCODE)
	YY_BREAK
case 74:
YY_USER_ACTION
# line 105 "scn2.l"
TOK(TABLE)
	YY_BREAK
case 75:
YY_USER_ACTION
# line 106 "scn2.l"
TOK(TO)
	YY_BREAK
case 76:
YY_USER_ACTION
# line 107 "scn2.l"
TOK(UNION)
	YY_BREAK
case 77:
YY_USER_ACTION
# line 108 "scn2.l"
TOK(UNIQUE)
	YY_BREAK
case 78:
YY_USER_ACTION
# line 109 "scn2.l"
TOK(UPDATE)
	YY_BREAK
case 79:
YY_USER_ACTION
# line 110 "scn2.l"
TOK(USER)
	YY_BREAK
case 80:
YY_USER_ACTION
# line 111 "scn2.l"
TOK(VALUES)
	YY_BREAK
case 81:
YY_USER_ACTION
# line 112 "scn2.l"
TOK(VIEW)
	YY_BREAK
case 82:
YY_USER_ACTION
# line 113 "scn2.l"
TOK(WHENEVER)
	YY_BREAK
case 83:
YY_USER_ACTION
# line 114 "scn2.l"
TOK(WHERE)
	YY_BREAK
case 84:
YY_USER_ACTION
# line 115 "scn2.l"
TOK(WITH)
	YY_BREAK
case 85:
YY_USER_ACTION
# line 116 "scn2.l"
TOK(WORK)
	YY_BREAK
	/* punctuation */
case 86:
YY_USER_ACTION
# line 121 "scn2.l"
case 87:
YY_USER_ACTION
# line 122 "scn2.l"
case 88:
YY_USER_ACTION
# line 123 "scn2.l"
case 89:
YY_USER_ACTION
# line 124 "scn2.l"
case 90:
YY_USER_ACTION
# line 125 "scn2.l"
case 91:
YY_USER_ACTION
# line 125 "scn2.l"
TOK(COMPARISON)
	YY_BREAK
case 92:
YY_USER_ACTION
# line 127 "scn2.l"
TOK(yytext[0])
	YY_BREAK
	/* names */
case 93:
YY_USER_ACTION
# line 131 "scn2.l"
TOK(NAME)
	YY_BREAK
	/* parameters */
case 94:
YY_USER_ACTION
# line 134 "scn2.l"
{
			save_param(yytext+1);
			return PARAMETER;
		}
	YY_BREAK
	/* numbers */
case 95:
YY_USER_ACTION
# line 142 "scn2.l"
case 96:
YY_USER_ACTION
# line 143 "scn2.l"
case 97:
YY_USER_ACTION
# line 143 "scn2.l"
TOK(INTNUM)
	YY_BREAK
case 98:
YY_USER_ACTION
# line 146 "scn2.l"
case 99:
YY_USER_ACTION
# line 147 "scn2.l"
case 100:
YY_USER_ACTION
# line 147 "scn2.l"
TOK(APPROXNUM)
	YY_BREAK
	/* strings */
case 101:
YY_USER_ACTION
# line 151 "scn2.l"
{
		int c = input();

		unput(c);	/* just peeking */
		if(c != '\'') {
			SV;return STRING;
		} else
			yymore();
	}
	YY_BREAK
case 102:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_USER_ACTION
# line 161 "scn2.l"
{	yyerror("Unterminated string"); }
	YY_BREAK
case 103:
YY_USER_ACTION
# line 163 "scn2.l"
{ save_str(" ");lineno++; }
	YY_BREAK
case 104:
YY_USER_ACTION
# line 164 "scn2.l"
{ lineno++; ECHO; }
	YY_BREAK
case 105:
YY_USER_ACTION
# line 166 "scn2.l"
save_str(" ");	/* white space */
	YY_BREAK
case 106:
YY_USER_ACTION
# line 168 "scn2.l"
;	/* comment */
	YY_BREAK
case 107:
YY_USER_ACTION
# line 170 "scn2.l"
ECHO;	/* random non-SQL text */
	YY_BREAK
case 108:
YY_USER_ACTION
# line 171 "scn2.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SQL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_input_file != yyin )
			{
			/* This can happen if we scan a file, yywrap() returns
			 * 1, and then later the user points yyin at a new
			 * file to resume scanning.  We have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input file.
			 */
			yy_current_buffer->yy_input_file = yyin;
			yy_n_chars = yy_current_buffer->yy_n_chars;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_eof_status = EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 409 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 409 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 408);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;


	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *yy_c_buf_p;
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

	b->yy_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_eof_status = EOF_NOT_SEEN;
	}


#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		int new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}


static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strcpy( char *s1, const char *s2 )
#else
static void yy_flex_strcpy( s1, s2 )
char *s1;
const char *s2;
#endif
	{
	while ( (*(s1++) = *(s2++)) )
		;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( unsigned int size )
#else
static void *yy_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, unsigned int size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 171 "scn2.l"


void
yyerror(char *s)
{
	printf("%d: %s at %s\n", lineno, s, yytext);
}

void
main(int ac, char **av)
{
	if(ac > 1 && (yyin = fopen(av[1], "r")) == NULL) {
		perror(av[1]);
		exit(1);
	}

	if(!yyparse())
		fprintf(stderr, "Embedded SQL parse worked\n");
	else
		fprintf(stderr, "Embedded SQL parse failed\n");
} /* main */

/* leave SQL lexing mode */
void
un_sql()
{
	BEGIN INITIAL;
} /* un_sql */
