# /usr/ports/comm/Makefile.inc 0.1	Jan 94	Julian Stacey <stacey@guug.de>
#	Copyright Julian Stacey, Munich Dec. 93, Free Software, No Liability.
#	For details see `Legalities' in /sys/Makefile.

SUBDIR =
G_SUBDIR =

G_SUBDIR += flexfax
SUBDIR += kermit
SUBDIR += rzsz
SUBDIR += term

.include <bsd.subdir_ports.mk>

# End of Makefile.
