/* sccsdata.c - sccs data file for wn generated by mksccs */

char wn_sccsdata_c_sccsid[] = "@(#)sccsdata.c	1.73 15/9/92";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  Add handling of greyscale visuals from vdburg@utrcsc.enet.dec.com
 *  Redo parse_x11_geometry based on versoion from der Mouse.
 *  Add code to handle app-defaults file from gregm@otc.research.otca.oz.au
 */

 const char *_wn_sccsdata[] = {
	"wn version 1.73 (build date: Tue Sep 15 18:06:14 BST 1992)",
	"@{$wn$}: sccsdata.c 1.73 ",
	"@{$wn$}: framed.h 1.2 ",
	"@{$wn$}: wn_framed.h 1.2 ",
	"@{$wn$}: wn_sunframe.h 1.2 ",
	"@{$wn$}: sccsdata.h 1.1 ",
	"@{$wn$}: wn.h 1.20 ",
	"@{$wn$}: wn_bm.h 1.2 ",
	"@{$wn$}: wn_color.h 1.3 ",
	"@{$wn$}: wn_cu.h 1.4 ",
	"@{$wn$}: wn_event.h 1.4 ",
	"@{$wn$}: wn_icon.h 1.2 ",
	"@{$wn$}: wn_init.h 1.2 ",
	"@{$wn$}: wn_misc.h 1.6 ",
	"@{$wn$}: wn_priv.h 1.15 ",
	"@{$wn$}: wn_replay.h 1.4 ",
	"@{$wn$}: wn_rop.h 1.2 ",
	"@{$wn$}: wn_sc.h 1.2 ",
	"@{$wn$}: wn_win.h 1.4 ",
	"@{$wn$}: wn_xrop.h 1.2 ",
	"@{$wn$}: wn_color.c 1.15 ",
	"@{$wn$}: wn_cu.c 1.13 ",
	"@{$wn$}: wn_sc.c 1.11 ",
	"@{$wn$}: wn_font.c 1.15 ",
	"@{$wn$}: wn_event.c 1.39 ",
	"@{$wn$}: wn_rop.c 1.17 ",
	"@{$wn$}: wn_xrop.c 1.12 ",
	"@{$wn$}: wn_mrop.c 1.12 ",
	"@{$wn$}: wn_bm.c 1.11 ",
	"@{$wn$}: wn_misc.c 1.26 ",
	"@{$wn$}: wn_init.c 1.44 ",
	"@{$wn$}: wn_win.c 1.22 ",
	"@{$wn$}: wn_sunframe.c 1.15 ",
	"@{$wn$}: wn_framed.c 1.10 ",
	"@{$wn$}: wn_icon.c 1.16 ",
	"@{$wn$}: wn_replay.c 1.14 ",
	"@{$wn$}: doc/wn.tex 1.1 ",
	"@{$wn$}: doc/wn-list.tex 1.1 ",
	"@{$wn$}: edump.c 1.5 ",
	"@{$wn$}: framed.c 1.10 ",
	"@{$wn$}: testwn.c 1.21 ",
	"@{$wn$}: Makefile 1.28 ",
};
