.\" $NCDId: @(#)issoundfile.man,v 1.1 1994/01/18 20:08:50 greg Exp $
.TH ISSOUNDFILE 1 "" "NCDware 3.2"
.SH NAME
issoundfile \- checks if a file is in a recognized audio file format
.SH SYNOPSIS
.B issoundfile
filename
.SH DESCRIPTION
The \fIissoundfile\fP program checks the specified file to see if it
is in one of the recognized audio file formats and, if it is, returns a
zero (true) exit status; otherwise, a non-zero (false) exit status is
returned.
.SH "SEE ALSO"
ncdaudio(1)
.SH COPYRIGHT
Copyright 1994 Network Computing Devices, Inc.
.SH AUTHOR
Greg Renda, Network Computing Devices, Inc.
