(*
	IDL -- a trivial example

	@(#)idl0.idl	2.1 93/03/07 00:58:13
*)

%{
#include <stdio.h>
main ()
{    idlinit("/dev/tty");
     fprintf(stderr, "IDL0\n");
     idlserver();
}
%}

estring(s:string)       :string     => s
estringl(s:string)      :string int = %{ int l = strlen(s); %} => s, l
eint(i:int)             :int        => i
quit()                  :unit       = %{ idlcontinue=0; %}     => ()

${
	fun lengths ss = map estringl ss
$}
