#! /bin/sh
# delversion - mail version to sender identified in stdin's headers

# =()<. ${NEWSCONFIG-@<NEWSCONFIG>@}>()=
. ${NEWSCONFIG-/usr/lib/news/bin/config}
export NEWSCTL NEWSBIN NEWSARTS
PATH=$NEWSCTL/bin:$NEWSBIN/relay:$NEWSBIN:$NEWSPATH ; export PATH
umask $NEWSUMASK

SENDER="`newsreply`"
(echo "Subject: response from `newshostname` to your version"; echo "";
echo "C, performance release"
) | mail "$SENDER"
echo "News version number has been sent to $SENDER.
Please remain calm.  DON'T PANIC.  This is perfectly routine.
Your version number is public information by definition.
This is a requirement of membership in Usenet.
Please don't waste everyone's time by asking about this on Usenet
or by harassing the person who sent the version control message." |
	mail $NEWSMASTER
