#! /bin/sh
##  $Revision: 1.1 $
##  Set up any and all shell variables that an INN shell script
##  might need.  Also sets umask.


##  =()<ACTIVE=@<_PATH_ACTIVE>@>()=
ACTIVE=/news/lib/active
##  =()<ACTIVETIMES=@<_PATH_ACTIVETIMES>@>()=
ACTIVETIMES=/news/lib/active.times
##  =()<AWK=@<_PATH_AWK>@>()=
AWK=/bin/gawk
##  =()<BATCH=@<_PATH_BATCHDIR>@>()=
BATCH=/news/spool/out.going
##  =()<COMPRESS=@<_PATH_COMPRESS>@>()=
COMPRESS=/usr/ucb/compress
##  =()<CONTROLPROGS=@<_PATH_CONTROLPROGS>@>()=
CONTROLPROGS=/news/bin/control
##  =()<CTLFILE=@<_PATH_CONTROLCTL>@>()=
CTLFILE=/news/lib/control.ctl
##  =()<CYCLES=@<LOG_CYCLES>@>()=
CYCLES=7
##  =()<DAILY=@<_PATH_LOCKS>@/LOCK.news.daily>()=
DAILY=/news/lib/LOCK.news.daily
##  =()<EGREP=@<_PATH_EGREP>@>()=
EGREP=/bin/egnugrep
##  =()<ERRLOG=@<_PATH_ERRLOG>@>()=
ERRLOG=/var/log/news/errlog
##  =()<CTLWATCH=@<_PATH_CTLWATCH>@>()=
CTLWATCH=/news/lib/innwatch.ctl
##  =()<HAVE_UUSTAT=@<HAVE_UUSTAT>@>()=
HAVE_UUSTAT=DO
##  =()<HISTORY=@<_PATH_HISTORY>@>()=
HISTORY=/news/lib/history
##  =()<INCOMING=@<_PATH_SPOOLNEWS>@>()=
INCOMING=/var/spool/rnews
##  =()<INEWS=@<_PATH_INEWS>@>()=
INEWS=/usr/local/bin/inews.nntp
##  =()<INNCONFVAL=@<_PATH_NEWSBIN>@/innconfval>()=
INNCONFVAL=/news/bin/innconfval
##  =()<INND=@<_PATH_INND>@>()=
INND=/news/bin/innd
##  =()<INNDDIR=@<_PATH_INNDDIR>@>()=
INNDDIR=/news/lib/innd
##  =()<INNDSTART=@<_PATH_INNDSTART>@>()=
INNDSTART=/news/bin/inndstart
##  =()<INNWATCH=@<_PATH_NEWSBIN>@/innwatch>()=
INNWATCH=/news/bin/innwatch
##  =()<LOCKS=@<_PATH_LOCKS>@>()=
LOCKS=/news/lib
##  =()<LOG=@<_PATH_LOGFILE>@>()=
LOG=/var/log/news/news
##  =()<MAILCMD=@<_PATH_MAILCMD>@>()=
MAILCMD=/usr/ucb/Mail
##  =()<MOST_LOGS=@<_PATH_MOST_LOGS>@>()=
MOST_LOGS=/var/log/news
##  =()<NEWACTIVE=@<_PATH_NEWACTIVE>@>()=
NEWACTIVE=/news/lib/active.tmp
##  =()<NEWSBIN=@<_PATH_NEWSBIN>@>()=
NEWSBIN=/news/bin
##  =()<NEWSCONTROL=@<_PATH_NEWSCONTROL>@>()=
NEWSCONTROL=/news/lib/innd/control
##  =()<NEWSFEEDS=@<_PATH_NEWSFEEDS>@>()=
NEWSFEEDS=/news/lib/newsfeeds
##  =()<NEWSGROUPS=@<_PATH_NEWSGROUPS>@>()=
NEWSGROUPS=/news/lib/newsgroups
##  =()<NEWSLIB=@<_PATH_NEWSLIB>@>()=
NEWSLIB=/news/lib
##  =()<NEWSMASTER=@<NEWSMASTER>@>()=
NEWSMASTER=usenet
##  =()<NEWSUSER=@<NEWSUSER>@>()=
NEWSUSER=news
##  =()<NNTPCONNECT=@<_PATH_NNTPCONNECT>@>()=
NNTPCONNECT=/news/lib/innd/nntpin
##  =()<OLDACTIVE=@<_PATH_OLDACTIVE>@>()=
OLDACTIVE=/news/lib/active.old
##  =()<RNEWS=@<_PATH_RNEWS>@>()=
RNEWS=/news/bin/rnews/rnews
##  =()<SED=@<_PATH_SED>@>()=
SED=sed
##  =()<SERVERPID=@<_PATH_SERVERPID>@>()=
SERVERPID=/news/lib/innd/innd.pid
##  =()<SLEEPTIME=@<INNWATCH_SLEEPTIME>@>()=
SLEEPTIME=600
##  =()<SPOOL=@<_PATH_SPOOL>@>()=
SPOOL=/news/spool
##  =()<STATUS=@<_PATH_INNWSTATUS>@>()=
STATUS=/news/lib/innwatch.status
##  =()<TEMPSOCK=`basename @<_PATH_TEMPSOCK>@ | ${SED} -e 's/XXXXXX$/*/'`>()=
TEMPSOCK=`basename /news/lib/innd/ctlinndXXXXXX | ${SED} -e 's/XXXXXX$/*/'`
##  =()<TEMPSOCKDIR=`echo @<_PATH_TEMPSOCK>@ | ${SED} -e 's@/[^/]*$@@'`>()=
TEMPSOCKDIR=`echo /news/lib/innd/ctlinndXXXXXX | ${SED} -e 's@/[^/]*$@@'`
##  =()<WATCHPID=@<_PATH_WATCHPID>@>()=
WATCHPID=/news/lib/innwatch.pid
##  =()<Z=@<_PATH_COMPRESSEXT>@>()=
Z=.Z

LOCALGROUPS=${NEWSLIB}/localgroups

##  =()<TMPDIR=${TMPDIR-@<_PATH_TMP>@}>()=
TMPDIR=${TMPDIR-/tmp}
export TMPDIR
PATH=${NEWSBIN}:${PATH}:/bin:/usr/bin:/usr/ucb
export PATH

##  =()<umask @<NEWSUMASK>@>()=
umask 0
