# /usr/ports/game/Makefile Thu Feb 17 17:26:04 MEZ 1994	Julian Stacey <stacey@guug.de>
#	Copyright Julian Stacey, Munich Dec. 93, Free Software, No Liability.
#	For details see `Legalities' in /sys/Makefile.

SUBDIR =
G_SUBDIR =

SUBDIR += golddig
SUBDIR += nethack
SUBDIR += seahaven
SUBDIR += xboing
SUBDIR += xjewel
SUBDIR += xpilot
SUBDIR += xtrek

.include <bsd.subdir_ports.mk>

# End of Makefile.
# $Id: Makefile,v 1.5 1994/05/23 11:31:34 sean Exp $
