#!/bin/sh
cd /usr/local/lib/dgd
if [ -e bin/driver ]; then
    echo "DGD seems to be already installed in /usr/local/lib/dgd."
    echo "The dgd_bin package cannot be installed or deleted while bin/driver exists."
    if [ $2 = "INSTALL" ]; then
        kill -15 0
    fi
    exit 1
fi
grep -q "^mud:" /etc/passwd
if [ $? -ne 0 ]; then
    echo "'mud' user must exist"
    exit 1
fi
grep -q "^mudadmin:" /etc/group
if [ $? -ne 0 ]; then
    echo "'mudadmin' group must exist"
    exit 1
fi
