# Copyright (C) 1993 John W. Eaton

# John W. Eaton
# jwe@che.utexas.edu
# Department of Chemical Engineering
# The University of Texas at Austin

# run some tests

proc octave_torture { file } {
    global comp_output

    set comp_output ""

    octave_start $file
    if [string match "*a-ok" "$comp_output"] then {
        pass "$file"
        return 0
    }
    fail "$file"
    return -1
}

foreach file [lsort [glob -nocomplain $srcdir/$subdir/*.oct]] {
    octave_torture $file
}
