/* XPM */
static char *emblem[] = {
/* width height ncolors chars_per_pixel */
"   80     44     4            1",
/* colors */
"  m white	c white",
"A m black	c black",
". m black	c DeepSkyBlue",
"c m white	c red",
/* pixels */
"                                                                    AAAA        ",
"                                                             AAAAAAA    AA      ",
"                                                            AA A A       AA     ",
"                                                            A   AAA      AA     ",
"                 .....                                     AA  AAA       AAA    ",
"             .........                                     A              A     ",
"           ...........                                    AA    AA        A     ",
"          ............                         AAAAAA     A   A  AAAAAAAAAA     ",
"         .............                      AAAAcccAAAAAAA        AccA   AA     ",
"        ..............                   AAAAAccccccccccAA         AAA          ",
"       ...............                  AcAAAccccccccccAA    A      AA          ",
"      ................                 AccAAcccccccccccA    AAA      A          ",
"     .................                AccAcccccccccccccA    A AAAAA    A        ",
"     .................               AccccccccccAccccAAAAAAAA     AAAAAA        ",
"     .................              AAccccccccAccccA      A AA      AA   AA AA  ",
"    ...............                AAAccccccAcccAA     A  AA A          AA    A ",
"    .............                 AAAccccccccccAAA       AAA AAAA      AA AA  A ",
"    ............                 AAAAccccAAcccA         AA   A   AAAAAAA AA   A ",
"   ............                  AcAccccAAccAA    A     AA   A AA AA      A   A ",
"   ............                 AccccccAAccAAA    A   AAA   AA   A        AA  A ",
"   ...........                  AccccccAccA  A      AA  A   A A      AAA AAAAA  ",
"   ...........                  AcccccAccA   A          AA AA AA   AAAAAA       ",
"   ...........  AAAAAAAAAAA     AcccccccA    A           AAAAAAAAAAAAAAAAA      ",
"                AAAAAAAAAAA    AccccAccA     A A         AcA   AAccccccccAA     ",
"                AAAAAAAAAAA    AcccAAccA      AA         AcAA   AccccccccAA     ",
"               AAAAAAAAAAAA    ccccAccA        AAA AAAAAAccAA  AcccccccccAA     ",
"               AAAAAAAAAAAA    AcccccA           AAcccccccccAA AcccccccccAA     ",
"              AAAAAAAAAAAA     AccccA           AAAAAcccccccAA AcccccccAAAA     ",
"            AAAAAAAAAAAAAA     AAcccA           AA AcccccccccAAccccccccAAAA     ",
"           AAAAAAAAAAAAAAA     AcccAAAA         A  AcccccccccAAcccccccccAA      ",
"        AAAAAAAAAAAAAAAAA      AcccA   A       A   AcccccccccAccccAcccccAA      ",
"        AAAAAAAAAAAAAAAAA      AccAA          A    AccccAcccccccccAcccccAA      ",
"        AAAAAAAAAAAAAAAA       AccA     A   AA    AcccccAcccccccccAcccccAA      ",
"        AAAAAAAAAAAAAAA        AccA     AA AA   AAAcccccAAcccccccAAAcccccAA     ",
"        AAAAAAAAAAAAAAA        AcAA     A AA   AAAAcccccAAcccccccAAAcccccAA     ",
"        AAAAAAAAAAAAAA         AcA      AA    A AAAccccAA AcccccAA AcccccAA     ",
"        AAAAAAAAAAAAA           AA      AA  AA  AAAccccAAAAcccccAAAAcccccAAA    ",
"        AAAAAAAAAAA             AA      AAA   AAAccccccccAAcccccAAAcccccccccA   ",
"        AAAAAAAAAA               A     A     AA AccccccccAAAcccAAAAcccccccccAA  ",
"        AAAAAAAA                A       AA   AAAAccccccccAAAcccAA AcccccccccAA  ",
"        AAAAA                      A     AAA   AAccccccccAA AcAA  AcccccccccAA  ",
"                                AA A  A  AAAAAAAAAAAAAAAAAA AAAA  AAAAAAAAAAAA  ",
"                                  AAAAAAAA      AAAAAAAAAAA  AA   AAAAAAAAAAAA  ",
"                                                                                "
};
