.TH TEX 1 2/2/84
.UC 4
.SH NAME
TEX \- 
.I TeX
and
.I LaTeX
typesetter and printer.
.SH SYNOPSIS
.B TEX
[
options
]
.I  filename
.SH DESCRIPTION
.I TEX
processes a file 
and sends it to a printer. The default is the Imagen; other devices 
can be used if available at the site.
.PP
The input to
.I TEX
does not have to be the raw manuscript.
.I TEX
can be given a
.I .dvi
file (which results from using the
.B -d
option),
or
.I .imp
and
.I .ver
files (which result from using the
.B -q
option), and it will proceed from and end at the appropriate stage.
.br
The file name does not have to end with
.I
tex.
.sp 2
OPTIONS :
.br
.TP
.B \-latex
uses LaTeX.  See the LaTeX manual.
.TP
.B \-x
makes two passes on the
.I LaTeX
input to resolve cross-references.
.TP
.B \-eqn
uses
.B
texeqn
to extract the equations.
.TP
.B \-log
saves messages from the
.B tex
run in 
.I filename
.B .log
and saves messages from LaTeX run in 
.I filename
.B .aux
.TP
.B \-d
quits once the
.I dvi
file is produced without producing a hardcopy.
.TP
.B \-q
(for quiescent) intermediate output is not spooled 
to the printing device.
.TP
.B \-v
output device is the varian (default is the imagen).
.fi
.SH SEE ALSO
tex(1), texeqn(1), texmatch(1), detex(1)
.SH FILES
file.aux			the auxiliary file used by LaTeX for labeling figures.
.br
The default is to remove the following files at the end of the run:
.br
TE????.dvi		the device independent file.
.br
TE????.log		the log file.
.br
TE????.imp		the impress file; can be printed by
.B ipr
file.
.SH BUGS
Only one file can be processed at a time.
.br
Drivers flags are not incorporated. Add the ones you need.
.SH AUTHOR
Kamal Al-Yahya
.br
Jeff Thorson
.br
Chuck Sword
