.TH texexpand 1 7/10/86
.UC 4
.SH NAME
texexpand \- expands TeX's \\input and LaTeX's \\input{} and \\include{}.
.SH SYNOPSIS
.B texexpand [-w]
.I filename
.SH DESCRIPTION
A TeX or LaTeX document can have included files.
.I Texexpand
rewrites the document after inserting these files. The name of the
included file has to be correct relative to the current working
directory. If
.I filename
cannot be opened, it will try to open
.I filename.tex.
The character '%' is recognized as a comment indicator and the commented
text is passed to the output without opening inserted files in that line.
.br
Warning is given if suspected unmatching is detected. Use the
.B -w
flag to suppress these warnings.
.SH SEE ALSO
texeqn(1), texmatch(1), detex(1).
.SH DIAGNOSTICS
Nesting of \\input and \\include is allowed but the number of opened files
must not exceed the system's limit on the number of simultaneously opened
files (normally < 20).
.br
LaTeX's \\includeonly is not recognized.
.SH AUTHOR
Kamal Al-Yahya, Stanford University, 7/10/86
