.TH texeqn 1 2/2/84
.UC 4
.SH NAME
texeqn \- extracts displayed equations in TeX and LaTeX documents.
.SH SYNOPSIS
.B texeqn [-iw]
.I filename
.SH DESCRIPTION
It is sometimes desirable to check only the equations of a document.
.I Texeqn
strips those patterns that constitute displayed equations, i.e. anything
surrounded by
.I two
dollar signs, \\begin{equation} and \\end{equation},
\\begin{eqnarray} and \\end{eqnarray}, or \\begin{displaymath} and
\\end{displaymath}.
Note that this also includes any text that is displayed
in this fashion even if it is not an equation.
.br
Macros defines by \\def or \\newcommand are also stripped, since
the user is likely to use them in those equations.
Also, \\input and \\include files are inserted unless the
.B -i
flag is used.
.br
Warning is given if suspected unmatching is detected. Use the
.B -w
flag to suppress these warnings.
.br
Text commented by '%' is ignored.
.br
Using 
.I texeqn 
alone does not typest the equations. If you want them typeset use the
.B \-eqn
option with TEX(1).
.SH DIAGNOSTICS
Displayed equations that are started and ended by user-defined
control sequences are nor recognized.
.br
White spaces within LaTeX's \\begin{...} and \\end{...} are not allowed for.
.SH SEE ALSO
TEX(1), detex(1), texexpand(1), texmatch(1)
.SH AUTHOR
Kamal Al-Yahya, Stanford University
