.TH texmatch 1 7/10/86
.UC 4
.SH NAME
texmatch \- checks matching in TeX and LaTeX documents.
.SH SYNOPSIS
.B texmatch [-i]
.I filename
.SH DESCRIPTION
.I Texmatch
gives error messages if it detects unmatched delimiters.
Delimiters are
braces, brackets, parentheses, dollar signs (single and double),
and LaTeX's \\begin and \\end. 
Error messages are sent to the standard error.
.br
Escaped braces and dollar signs are not counted.
\\input and \\include files are also checked unless the
.B -i
flag is used.
.br
Text, displayed equations, and environments are checked independently,
while commented text is not checked.
.SH DIAGNOSTICS
LaTeX environments that are started and ended by user-defined
control sequences are regarded as ordinary text and they are not checked
independently.
.br
White spaces within LaTeX's \\begin{...} and \\end{...} are not allowed for.
.SH SEE ALSO
texexpand(1), texeqn(1).
.SH AUTHOR
Kamal Al-Yahya, Stanford University
