.\" $Id: hfs.1,v 1.1 1994/05/15 05:44:52 rich Exp $
.\" $Log: hfs.1,v $
.\" Revision 1.1  1994/05/15 05:44:52  rich
.\" Initial revision
.\"
.\" Revision 1.3  1994/01/11  02:21:35  craigs
.\" Fixed problems with cat help and changed to version 0.3
.\"
.\" Revision 1.2  1994/01/06  03:10:52  craigs
.\" Added comment about usage messages
.\"
.\" Revision 1.1  1994/01/06  03:05:42  craigs
.\" Initial revision
.\"
.\"
.TH HFS 1 "12 January 1994"
.SH NAME
hfs \- program for accessing Macintosh HFS floppy disks
.SH SYNOPSIS
.B hfs
.BI ls
[
.BI \-laR
]
.BI filespec
.br
.B hfs
.BI dir
filespec
.br
.B hfs
.BI cd
directory
.br
.B hfs
.BI pwd
.br
.B hfs
.BI read
[
.BI \-tMR
]
hfsspec ... native_file
.br
.B hfs
.BI cat
[
.BI \-txR
]
filename

.SH DESCRIPTION
.I hfs
provides a command line interface to suite of functions for accessing
Macintosh HFS floppy disks. The following functions are available:
.TP 30
\- display a directory listing (ls, dir)
.TP 30
\- change directories (cd)
.TP 30
\- display the name of the current directory (pwd)
.TP 30
\- copy an HFS file into a local file (read)
.TP 30
\- display the contents of an HFS file (cat)
.TP 0
Functions may be invoked by specifiying the function name
on the command line followed by any parameters. Alternatively,
the executable can be copied or linked to an alternate name which
can then be used to invoke the function directly. The alternate
names recognised by
.B hfs are 
.B hls,
.B hdir,
.B hcd,
.B hpwd,
.B hread
and
.B hcat.

.I hfs
defaults to using the device
.I /dev/fd0H1440
to access the floppy drive. This can be overridden by
setting the environment variable
.I HFS_DEVICE
to the name of an alternate file or device. The special names
.I A:
and
.I B:
are synonyms for the devices 
.I /dev/fd0H1440
and
.I /dev/fd1H1440
respectively.

All paths specified on the HFS volume assume that the colon (":") character
is the directory separator character. The dot (".") character may be used
to indicate the current directory, and the double-dot ("..") sequence may
be used to indicate the parent directory.

Filename globbing accepts the standard Unix wildcard conventions.

The current version of 
.B hfstools
is 0.30

.SH OPTIONS
.TP
.B \-a 
display all files, including invisible ones
.TP
.B \-l
display file information in long format
.TP
.B \-t
convert Macintosh end\-of\-line characters (linefeeds) to the 
end\-of\-line sequence appropriate for the host operating system.
.TP
.B \-x
display the file in hex.
.TP
.B \-R
for the 
.I ls
command, display sub directories recursively. For the
.I read
and
.I cat
commands, use the resource fork rather than the data fork.
.TP
.B \-M
Do not attempt to mangle the filenames to be legal for the native operating system.

.SH ENVIRONMENT
.TP 15
.SB HFS_DEVICE
Specifies the name of the device used to access the floppy drive.

.SH BUGS
No functions for writing to the disk at the file level have yet been
implemented.

Wildcard expansion of HFS filenames has been implemented for the 
.Bhread
command, but not for the 
.B hls
command.

The usage messages need more work.

There is no support for the AppleDouble format.

There is no support for media other than standard 1.4 Mbyte floppy
disks, although there is no reason why this could not be added.

There is no support for MFS disks.

There is no support for 800K disks, as this is not possible with 
the vast majority of floppy disk hardware.

