.TH CTIME 1 local
.DA 23 April 1986
.SH NAME
ctime, getdate \- date conversions to and from numeric form
.SH SYNOPSIS
.B ctime
seconds ...
.br
.B getdate
date ...
.SH DESCRIPTION
.I Ctime
converts one or more Unix-internal (number of seconds since 1 Jan 1970)
dates into a human-readable form, as supplied by
.IR ctime (3).
.I Getdate
does the inverse, as done by
.IR getdate (3).
.PP
.I Getdate
actually accepts a somewhat wider range of input than just output from
.I ctime
or
.IR date (1);
see
.IR getdate (3)
for details.
Note that each
.I date
fed to
.I getdate
must be \fIone\fR argument;
it may be necessary to enclose it in quotes.
.SH SEE ALSO
ctime(3), getdate(3), date(1)
.SH DIAGNOSTICS
.I Getdate
will object and exit with a status of 1 if it cannot make sense of a
.IR date .
.SH HISTORY
Slightly-modified versions of programs written by Geoff Collyer at UTCS.
