# /usr/ports/print/Makefile Thu Feb 17 17:26:04 MEZ 1994	Julian Stacey <stacey@guug.de>
#	Copyright Julian Stacey, Munich Dec. 93, Free Software, No Liability.
#	For details see `Legalities' in /sys/Makefile.

SUBDIR =
G_SUBDIR =

SUBDIR += afm
SUBDIR += dvi2lj
SUBDIR += tex
SUBDIR += texinfo

.include <bsd.subdir_ports.mk>

# End of Makefile.
