.TH atktopbm 1 "26 September 1991"
.IX atktopbm
.SH NAME
atktopbm - convert Andrew Toolkit raster object to portable bitmap
.SH SYNOPSIS
.B atktopbm
.RI [ atkfile ]
.SH DESCRIPTION
Reads an Andrew Toolkit raster object as input.
.IX "Andrew Toolkit raster object"
Produces a portable bitmap as output.
.SH "SEE ALSO"
pbmtoatk(1), pbm(5)
.SH AUTHOR
Copyright (C) 1991 by Bill Janssen.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
