.TH pbmtoatk 1 "26 September 1991"
.IX pbmtoatk
.SH NAME
pbmtoatk - convert portable bitmap to Andrew Toolkit raster object
.SH SYNOPSIS
.B pbmtoatk
.RI [ pbmfile ]
.SH DESCRIPTION
Reads a portable bitmap as input.
Produces a Andrew Toolkit raster object as output.
.IX "Andrew Toolkit raster object"
.SH "SEE ALSO"
atktopbm(1), pbm(5)
.SH AUTHOR
Copyright (C) 1991 by Bill Janssen.
.\" Permission to use, copy, modify, and distribute this software and its
.\" documentation for any purpose and without fee is hereby granted, provided
.\" that the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.  This software is provided "as is" without express or
.\" implied warranty.
