/* sccsdata.c - sccs data file for ukcprog generated by mksccs */

char ukcprog_sccsdata_c_sccsid[] = "@(#)sccsdata.c	1.5 19/9/92";

#include "ukcprog.h"


#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  alloc.c: Ensure that space returned by alloc is always double aligned
 */

static const char *_ukcprog_sccsdata[] = {
	"ukcprog version 1.5 (build date: Sat Sep 19 14:23:39 BST 1992)",
	"@{$ukcprog$}: sccsdata.c 1.5 ",
	"@{$ukcprog$}: ukcprog.h 1.18 ",
	"@{$ukcprog$}: ukcheaders/ukcstdlib.h 1.1 ",
	"@{$ukcprog$}: ukcheaders/ukcstring.h 1.1 ",
	"@{$ukcprog$}: alloc.c 1.6 ",
	"@{$ukcprog$}: e_malloc.c 1.7 ",
	"@{$ukcprog$}: e_realloc.c 1.6 ",
	"@{$ukcprog$}: errf.c 1.10 ",
	"@{$ukcprog$}: formf.c 1.16 ",
	"@{$ukcprog$}: panic.c 1.7 ",
	"@{$ukcprog$}: ssplit.c 1.5 ",
	"@{$ukcprog$}: strf.c 1.5 ",
	"@{$ukcprog$}: strnf.c 1.1 ",
	"@{$ukcprog$}: strsave.c 1.5 ",
	"@{$ukcprog$}: fpgetline.c 1.4 ",
	"@{$ukcprog$}: strtol.c 1.4 ",
	"@{$ukcprog$}: config.c 1.2 ",
	"@{$ukcprog$}: ip.c 1.3 ",
	"@{$ukcprog$}: doc/ukcprog.3 1.14 ",
	"@{$ukcprog$}: Makefile 1.12 ",
};

const char *
ukcprog_version()
{
	return _ukcprog_sccsdata[0];
}
