#!/bin/sh
# gnuplot "prerequesites" script---checks for existence of libreadline.so.*
this=gnuplot
required=libreadline
if [ "$2" != "INSTALL" ]; then
  exit 0	# nothing to check on deinstallation
fi
echo "Okay!  So you are trying to install the $this binary distribution!"
echo "That's great!  But let me check if you have the correct library,"
echo "since this is compiled shared and if you don't have"
echo "$required somewhere, it won't run!"
echo " "
echo "Now let me check...."
echo " "
if ldconfig -r | grep -e ':-lreadline\.1\.. =>' >/dev/null 2>&1; then
  echo "Congratulations!  You've got $required on your system!  You can"
  echo "run $this!"
  echo " "
  echo "I'm now going ahead with the installation.  Bye...."
  exit 0
else
  echo "(dim face) Things don't look good, my friend.  I can't find"
  echo "$required in your shared library cache.  What I did was"
  echo "\"ldconfig -r\", by the way."
  echo " "
  echo "But there is still hope.  You may have installed $required on"
  echo "your system recently and just haven't run ldconfig to notify"
  echo "the OS of its existence.  If that's the case, please try"
  echo "looking into /etc/rc and run ldconfig as root.  The command"
  echo "line should be something like:"
  echo " "
  echo "ldconfig /usr/lib /usr/X386/lib /usr/local/lib /usr/gnu/lib"
  echo " "
  echo "(this is just an example, make sure to check /etc/rc before"
  echo " running it, as you can screw up your system if you get it"
  echo " wrong!)".
  echo " "
  echo "If you haven't gotten $required yet, you can get it from the"
  echo "FreeBSD-current archive under src/gnu/lib/$required, probably at"
  echo "the same site as you got this package."
  echo "Please install that package before you run $this, okay?"
  echo " "
  echo "Anyway, whatever you decide, I'll give you the final choice"
  echo "of whether installing $this now or not.  You can either"
  echo "install $this now and sort out $required later, or quit the"
  echo "installation for now and come back later after getting $required"
  echo "to work.  Do you want to continue with the installation? (y/n)"
  ans=""
  while true; do
    echo -n "your answer goes here ==> "
    read ans
    case x"$ans" in
      x[yY])
	echo "Okay, then I'll go ahead with the installation.  Bye...."
	exit 0
	;;
      x[nN])
	echo "Okay, I'll quit the installation for now.  See you later...."
	exit 1
	;;
    esac
    echo "Well, I need you to say either \"yes\" or \"no\".  You know,"
    echo "I'm kinda stupid and can't make up my mind.  So please let me"
    echo "repeat my question, do you want to continue with the"
    echo "installation? (y/n)"
  done
fi
