.TH AD 1 LOCAL
.SH NAME
ad \- play adagio or translate to midi
.SH SYNOPSIS
.B ad
[ options ] file [ options ]
.SH DESCRIPTION
.I Ad
plays an
.B Adagio
score on an fm sound card under
.I Linux
or translates it into the track portion of a standard
.B midi
file with output to
.IR stdout .
One or more such tracks can be combined into
form a standard
.B midi
file with the utility
.IR tracks .
.PP
If a file with the name supplied on the command line is not
found,
.I ad
supplies the suffix ".gio" and looks again.
.PP
The playing routine of
.I ad
is identical with that of the playing programs
.IR mp and xmp ,
and it also uses cfg configuration files in the same
way as those programs (except for track and channel
assignments), so please refer to mp(1) and
xmp(1) for details.
The Adagio scoring language does not currently provide
for setting chorus depth or reverberation.
.PP
There are the following command line options:
.TP
.BR \-external \ (or \ \-e )
means don't send any channels to the external midi port.
(Which channels will be external, if any, in the absence of
this flag, depends on a compilation option -- see the Makefile.)
.TP
.BR \-p
plays all parts except percussion with piano, ignoring program
requests.
.TP
.BR \-r \ chan[,prog]
records midi input from the external port in a new file "mpout.mid".
"Chan" is a number from 1-16, the channel for the midi commands in
the file, and "prog" is a number from 0-127, for the general midi
program to be used.  The output midi file contains a single track
which can be merged with the file being played by the separate
utility programs
.IR midt \ and \ tm .
.TP
.BR \-s
prevents treating any instruments as "solo" or non-polyphonic instruments.
A new note on a solo instrument cuts off any previous note (e.g.,
on a flute as opposed to piano).
.TP
.BR \-midi \ (or \ \-m )
translates instead of playing.
.TP
.B \-help
displays a usage summary.
.TP
.BR \-init \ (or \ \-i )
prevents a series of initialization commands for
each channel from being issued at the beginning of
the track.
.TP
.B \-v
gives some information about
which programs are used for which voices, and some
other things.
.TP
.B \-vv
gives even more information than
.B \-v
does.
.TP
.BR \-tune \ file
uses tuning information from the file.
.TP
.BR \-trace \ (or \ \-t )
issues tracing information.
.SH "SEE ALSO"
mp(1), setfm(1), tracks(1), midt(1), ``The CMU Midi Toolkit'' by Roger Dannenberg
.SH BUGS
This version of the Adagio language does not provide means to
set all midi controllers -- only numbers 1, 5, 64, and 65.
Consequently, other controller information is lost in the
translation from midi to adagio done by "mp -a".
.br
There is no provision for drum roll notes (notes > 81 on a
percussion channel).
.SH AUTHORS
Roger Dannenberg,
Roger.Dannenberg@SPICE.CS.CMU.EDU,
(Adagio and Transcribe interpreter code),
.br
Greg Lee, lee@uhunix.uhcc.hawaii.edu
(the rest).
