.TH MT 1 LOCAL
.SH NAME
tm, midt \- assemble and disassemble midi files
.SH SYNOPSIS
.B tm
[ file [ file ... ] ]
.br
.B midt
[
.B \-d
] [
.B \-s
] [
.B \-q
]  [ file ]
.SH DESCRIPTION
.I Midt
disassembles a standard
.B midi
file into readable/editable text, and
.I tm
assembles the text form back into a midi file.
If no file is mentioned, input is from
.IR stdin .
.I Midt
prefers the file suffix ".mid" -- it will supply
it if a file by the name given on the command line cannot be found.
Its output is to
.IR stdout .
.I Tm
prefers the file suffix ".mt", and output is to a file
with the suffix ".mid" added or substituted for the ".mt"
suffix of the input file.  If input was
.IR stdin ,
the output file is named "tmout.mid".
.PP
Additional .mt files with one track each can be given to
.IR tm ,
in which case they are merged with the first file mentioned
on the command line to produce a midi file with additional
tracks.
.PP
There are the following options for
.IR midt :
.TP
.B \-d
displays times as deltas from the time of the last midi event.
This makes it easier to edit out or edit in parts of a track before
reassembling with 
.IR tm .
A keyword "DELTA" is placed in the header line in the disassembly
so that
.I tm
will know to interpret the times as deltas.
.TP
.B \-s
displays times in seconds and factions instead of midi ticks; the
format is "<seconds>.<centiseconds>.<16nths of a centisecond>".
(Combining
.B \-d
and
.B \-s
is not recommended if preparing input for
.IR tm ,
because this loses accuracy.)
.TP
.B \-q
suppresses note-on and note-off output lines.
.SH AUTHORS
The code for
.I midt
is a slight elaboration of the program
.I mftext
by Tim Thompson, ...twitch!glimmer!tjt,
who also wrote the first version of the library
functions in midifile.c, which were elaborated
for midi file output by M. Czeiszperger.
.br
rest is by
Greg Lee, lee@uhunix.uhcc.hawaii.edu.
