.TH TRACKS 1 LOCAL
.SH NAME
tracks \- combine midi tracks
.SH SYNOPSIS
.B tracks
filenames
.SH DESCRIPTION
.I Tracks
combines the
.B midi
binary information in files given as arguments,
adding track headers and trailers and a
.B midi
header at the beginning.
Output is to
.IR stdout .
.SH "SEE ALSO"
ad(1)
.SH BUGS
No time signature or tempo information is included.
.SH AUTHOR
Greg Lee, lee@uhunix.uhcc.hawaii.edu
