/* sccsdata.c - sccs data file for arg generated by mksccs */

char arg_sccsdata_c_sccsid[] = "@(#)sccsdata.c	1.19 18/9/92";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  Fix memory leaks reported by purify.
 */

 const char *_arg_sccsdata[] = {
	"arg version 1.19 (build date: Fri Sep 18 17:29:19 BST 1992)",
	"@{$arg$}: sccsdata.c 1.19 ",
	"@{$arg$}: arg_brace.c 1.10 ",
	"@{$arg$}: arg_dir.c 1.11 ",
	"@{$arg$}: arg_glob.c 1.10 ",
	"@{$arg$}: arg_lparse.c 1.10 ",
	"@{$arg$}: arg_match.c 1.9 ",
	"@{$arg$}: arg_quote.c 1.10 ",
	"@{$arg$}: arg_redir.c 1.10 ",
	"@{$arg$}: arg_user.c 1.10 ",
	"@{$arg$}: arg_vec.c 1.9 ",
	"@{$arg$}: arg_version.c 1.5 ",
	"@{$arg$}: testarg.c 1.9 ",
	"@{$arg$}: arg.h 1.6 ",
	"@{$arg$}: sccsdata.h 1.1 ",
	"@{$arg$}: Makefile 1.12 ",
};
