#!/bin/sh
if pkg_info -e tk_src && pkg_info -e tcl_src; then
	:;
else
	echo "This package also requires the tcl and tk packages."
	echo "Make sure you have them installed before trying to build this"
	echo "package for the first time."
	echo ""
fi
exit 0
