#!/bin/sh
# scales moon.xbm by a factor of $1 (default 0.5)
if [ ! -f moonorig.xbm ]; then # only first time
  mv moon.xbm moonorig.xbm
fi
if [ $# = 0 ]; then
  scale=0.5
elif [ $# = 1 ]; then
  scale=$1
else
  echo "usage: $0 [scale (default 0.5)]"
  exit 1
fi
xbmtopbm moonorig.xbm | pnmscale $scale | pgmtopbm | pbmtoxbm | \
  sed -e 's/noname/moon/g' > moon.xbm
