.\" =()<.ds c @<NEWSCTL>@>()=
.ds c /usr/lib/news
.TH CHECKNEWS 1 "23 Nov 1990"
.BY "C News"
.SH NAME
checknews \- check for unread news
.SH SYNOPSIS
.B checknews
.SH DESCRIPTION
.I Checknews
informs the user whether he has unread news.
It is suitable for running from a
.B .profile
(or
.B .login
if you use a certain non-standard shell)
file.
.PP
.I Checknews
normally runs
.IR readnews (1)
with the
.B \-c
option.
As a heuristic concession to practicality,
if the user has a
.B .rnlast
file in his $HOME directory,
.I checknews
runs
.B rn\ \-c\ \-s3
instead.
.SH FILES
$HOME/.newsrc
.br
\*c/active
.SH SEE ALSO
readnews(1), rn(1)
.SH HISTORY
Written at U of Toronto by Henry Spencer.
.SH BUGS
There are zillions of other news readers in the world.
