.\" =()<.ds a @<NEWSARTS>@>()=
.ds a /usr/spool/news
.\" =()<.ds b @<NEWSBIN>@>()=
.ds b /usr/lib/newsbin
.\" =()<.ds c @<NEWSCTL>@>()=
.ds c /usr/lib/news
.\" =()<.ds m @<NEWSMASTER>@>()=
.ds m usenet
.TH EXPLODE 8 "22 July 1991"
.BY "C News"
.SH NAME
explode \- expand a relaynews master batch file into all the ordinary batch files implied
.SH SYNOPSIS
.B explode
[ file ... ]
.SH DESCRIPTION
.I Explode
reads a master batch file produced by
.IR relaynews (8)
and writes all the plain batch files
described therein.
.I Explode
should be run in
.BR \*a ,
since the input file will almost certainly
contain path names relative to
.BR \*a .
.PP
The format of the input file(s) is
.LP
.nf
.in +0.5i
.ft B
# optional comments
<82756@uunet.uu.net> news/admin/12435 2097
F out.going/site1/togo
f \*a/out.going/site2/togo
n out.nntp/site3
I out.going/site4.wehave/togo
.ft
.in -0.5i
.fi
.LP
where
.B 2097
is the article size in bytes,
and
where
there is one
.B "<message-id>"
line per article and an
.BR F ,
.BR f ,
.B n
or
.B I
line
per site getting that article.
.SH "SEE ALSO"
.IR news (5),
.IR newsbatch (8),
.IR relaynews (8)
.SH HISTORY
Written by Geoff Collyer
at Software Tool & Die.
