.\" =()<.ds c @<NEWSCTL>@>()=
.ds c /usr/lib/news
.TH POSTNEWS 1 "21 Nov 1990"
.BY "C News"
.SH NAME
postnews \- simple interactive news-posting interface
.SH SYNOPSIS
.B postnews
[
.B \-h
headerfile
] [newsgroup]
.SH DESCRIPTION
.I Postnews
provides a simple interactive interface for posting news.
It prompts the user for the \fInewsgroup\fR if it is not given as an argument
(more than one group can be given, with groups separated by commas but no
white space),
prompts for the article's subject,
drops the user into his choice of text editor with a prototype
article,
checks (when the editor terminates) that the article has been edited
reasonably, and then posts it.
.PP
If the article has not been written out from the editor, or if the
editing instructions in the prototype do not appear to have been
followed, \fIpostnews\fR gives the user a choice between abandoning
the posting or re-editing it.
.PP
The
.B \-h
option specifies that a suitable header has already been constructed and
can be found in \fIheaderfile\fR, in which case \fIpostnews\fR bypasses
the initial prompting for header contents.
.SH FILES
\*c/postdefltgroup	default newsgroup (nonexistent means no default)
.br
\*c/postdefltdist	default distribution (nonexistent means `world')
.SH SEE ALSO
inews(1)
.SH HISTORY
Written at U of Toronto by Henry Spencer.
.SH BUGS
There are zillions of marginally-useful features that it could have
but doesn't.
