#include "scanner.h"
#include "sccs.h"

#include "protos.h"

SCCSID(@(#)s_cmap.c	8.1	12/31/84)

/* CHARACTER TYPE MAP */
static char	Cmap[] = {
	CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL,
	CNTRL, PUNCT, PUNCT, CNTRL, CNTRL, PUNCT, CNTRL, CNTRL,
	CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL,
	CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL, CNTRL,
	PUNCT, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR,
	OPATR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR,
	NUMBR, NUMBR, NUMBR, NUMBR, NUMBR, NUMBR, NUMBR, NUMBR,
	NUMBR, NUMBR, OPATR, OPATR, OPATR, OPATR, OPATR, OPATR,
	OPATR, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, OPATR, OPATR, OPATR, OPATR, ALPHA,
	OPATR, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA,
	ALPHA, ALPHA, ALPHA, OPATR, OPATR, OPATR, OPATR, OPATR,
	0
};

int
parser_cmap(char ch)
{
	return(Cmap[(int) ch]);
}
