      BLOCK DATA
C-----------------------------------------------------------------------
C THIS DATA SUBPROGRAM LOADS VARIABLES INTO THE INTERNAL COMMON
C BLOCKS USED BY THE ODEPACK SOLVERS.  THE VARIABLES ARE
C DEFINED AS FOLLOWS..
C   ILLIN  = COUNTER FOR THE NUMBER OF CONSECUTIVE TIMES THE PACKAGE
C            WAS CALLED WITH ILLEGAL INPUT.  THE RUN IS STOPPED WHEN
C            ILLIN REACHES 5. 
C   NTREP  = COUNTER FOR THE NUMBER OF CONSECUTIVE TIMES THE PACKAGE
C            WAS CALLED WITH ISTATE = 1 AND TOUT = T.  THE RUN IS
C            STOPPED WHEN NTREP REACHES 5.
C   MESFLG = FLAG TO CONTROL PRINTING OF ERROR MESSAGES.  1 MEANS PRINT,
C            0 MEANS NO PRINTING.
C   LUNIT  = DEFAULT VALUE OF LOGICAL UNIT NUMBER FOR PRINTING OF ERROR
C            MESSAGES.
C-----------------------------------------------------------------------
      INTEGER ILLIN, IDUMA, NTREP, IDUMB, IOWNS, ICOMM, MESFLG, LUNIT 
      DOUBLE PRECISION ROWNS, RCOMM
      COMMON /LS0001/ ROWNS(209), RCOMM(9),
     1   ILLIN, IDUMA(10), NTREP, IDUMB(2), IOWNS(6), ICOMM(19)
      COMMON /EH0001/ MESFLG, LUNIT
      DATA ILLIN/0/, NTREP/0/ 
      DATA MESFLG/1/, LUNIT/6/
C
C----------------------- END OF BLOCK DATA -----------------------------
      END 
