
 ...that is a hyperlink!

 HyperHelp Window
 ---------------------------------------------------------------

 As each link is traversed, the list of HyperHelp topics near
 the top of the HyperHelp window is updated.  An icon for each
 new help page is appended to a chain of icons.  Previous
 pages can be revisited by clicking on the corresponding page
 icon.

   %%
label $blt_htext(widget).full -bitmap hyperhelp-fullpage
$blt_htext(widget) append $blt_htext(widget).full
%% - represents the current page in the hyperlink chain
   %%
label $blt_htext(widget).empty -bitmap hyperhelp-emptypage
$blt_htext(widget) append $blt_htext(widget).empty
%% - represents any other page in the hyperlink chain

 At any point, the "Go Back" button can be pressed to delete
 the current help page, and move to the nearest page at the
 current position in the hyperlink chain.

 The "Dismiss" button is used to close the HyperHelp window.
