.\" t
.\" @(#)FvwmBanner.1	1/12/94
.TH FvwmBanner 1.20 "Jan 28, 1994"
.UC
.SH NAME
FvwmBanner \- the FVWM Banner
.SH SYNOPSIS
FvwmBanner is intended to be spawned by fvwm, but it will work if
run from the command line.

.SH DESCRIPTION
The FvwmInitBanner displays an Fvwm Logo in the center of the screen
for 5 seconds.

.SH COPYRIGHTS
None.

.SH INITIALIZATION
Nothing interesting.

.SH INVOCATION
FvwmBanner can be invoked by binding the action 'Module
FvwmBanner' to a menu or key-stroke in the .fvwmrc file.
Fvwm will search
directory specified in the ModulePath configuration option to attempt
to locate FvwmBanner. Although nothing keeps you from launching
FvwmBanner at start-up time, you probably don't want to.

.SH CONFIGURATION OPTIONS
There are no configuration options.

.SH AUTHOR
Robert Nation (nation@rocket.sanders.lockheed.com).

