#!/bin/sh
# Removes most all files that are not needed to re-build fvwm
#

rm -f */*.o 
rm -f */*~
rm -f */*.bak
rm -f */Makefile
rm -f *.bak
rm -f Makefile
rm -f */*.aux
rm -f */*.log
rm -f */*/*.o 
rm -f */*/*~
rm -f */*/*.bak
rm -f */*/Makefile
rm -f core*
rm -f */core*
rm -f */*/core*

rm -f fvwm/fvwm
rm -f modules/GoodStuff/GoodStuff
rm -f modules/FvwmClean/FvwmClean
rm -f modules/FvwmIdent/FvwmIdent
rm -f modules/FvwmBanner/FvwmBanner
rm -f modules/FvwmSave/FvwmSave
rm -f modules/FvwmDebug/FvwmDebug
rm -f modules/FvwmPager/FvwmPager
rm -f modules/FvwmWinList/FvwmWinList
rm -f xpmroot/xpmroot
rm -f decor_tester/decor_tester

rm -f */.??*
rm -f */#*#
rm -f */*/.??*
rm -f */*/#*#
rm -f .??*
#rm -rf binaries
rm -f *~




