#!/bin/sh
if [ ! -f fvwm.README ] ; then ; exit 1 ; fi

cp configurations/FreeBSD.h configure.h
cd xpmroot
cp ../fvwm/xpm.h xpm.h
cp ../configure.h configure.h
cd ..
cd modules/GoodStuff
cp ../../fvwm/alpha_header.h alpha_header.h
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cp ../../fvwm/xpm.h .
cd ../FvwmBanner
cp ../../configure.h .
cp ../../fvwm/xpm.h .
cp ../../fvwm/sun_headers.h .
cp ../../fvwm/alpha_header.h .
cd ../FvwmDebug
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cd ../FvwmClean
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cd ../FvwmSave
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cd ../FvwmIdent
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cd ../FvwmPager
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cp ../../fvwm/fvwm.h .
cd ../FvwmWinList
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
cd ../FvwmSound
cp ../../fvwm/alpha_header.h .
cp ../../configure.h .
cp ../../fvwm/module.h .
cp ../../fvwm/sun_headers.h .
cp ../../version.h .
