# /usr/ports/local/Makefile.inc 0.1	Jan 94	Julian Stacey <stacey@guug.de>
#	Copyright Julian Stacey, Munich Dec. 93, Free Software, No Liability.
#	For details see `Legalities' in /sys/Makefile.

SUBDIR =
G_SUBDIR =

SUBDIR += snd-util
SUBDIR += sounds

.include <bsd.subdir_ports.mk>

# End of Makefile.
