#! /bin/csh 
# File: sac-it
# Author: Heinz Schmidt (hws@ICSI.Berkeley.EDU)
# Copyright (C) International Computer Science Institute, 1991
#*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#* FUNCTION: sac-it -- call emacs on a sac file
#*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

if ( $?SATHER_HOME == 0 ) then
	echo The environment variable SATHER_HOME needs to be set'.'
	exit
endif
setenv SACFILE $1
emacs -batch -l $SATHER_HOME/sac/sac-it.el -f compile-SACFILE



