.TH FONTMAG 1 NYU
.SH NAME
fontmag \- magnify an RST font
.SH SYNOPSIS
fontmag [-m \fImag\fR] [-p \fIpsize\fR] infile outfile
.SH DESCRIPTION
.I Fontmag
is a tool to magnify RST raster font files.  It takes as input the
raster file
.I infile.
The magnfied raster file is written on the file
.I outfile.
.PP
.I Fontmag
supports several options:
.TP 5
\-m
The next argument specifies the magnification factor explicitly.
.TP 5
\-p
The next argument specifies the desired point size of the output
(magnified) raster.  The magnification is determined automatically.
.PP
If no arguments are specified,
.I fontmag
will try to guess the appropriate output point size from the file
name.
.SH SEE ALSO
rst(5)
.SH DIAGNOSTICS
Self explanatory
.SH BUGS
In general, the greater the magnification factor deviates from unity, the
worse the raster looks.  Therefore, it is best to magnify
font files as little as possible.
