#! /bin/sh
#
# script written by Alistair G. Crooks (agc@uts.amdahl.com)
# to use RCS to check-in all source files that have changed
#

echo "Reason for checkin?"
read reason
for i in *;
do
	if [ -d $i ]
	then
		if [ -d $i/RCS ]
		then
			echo "===> $i"
			( cd $i ; ci -l -m"$reason" *.[chyq] Makefile.in)
		fi
	fi
done
# get rid of files that aren't primary files
# they just confuse things...
rm -f support/ingres.c support/RCS/ingres.c,v
rm -f support/ingconv.c support/RCS/ingconv.c,v
