#! /bin/sh
#
# script written by Alistair G. Crooks (agc@uts.amdahl.com)
# to use RCS to check-out all source files that have changed
# after a disastrous editing session
#

for i in *;
do
	if [ -d $i ]
	then
		if [ -d $i/RCS ]
		then
			echo "===> $i"
			( cd $i ; co -l *.[chyq] Makefile.in)
		fi
	fi
done
# get rid of files that aren't primary files
# they just confuse things...
rm -f support/ingres.c support/RCS/ingres.c,v
rm -f support/ingconv.c support/RCS/ingconv.c,v
