#!/bin/sh

passwd=HNAMEPASS
while true
do
    mv 2.4.5/lpmud.log 2.4.5/lpmud.log.old
    date > 2.4.5/lpmud.log
#   bin/hname 6047 $passwd &
    bin/driver lpmud >> 2.4.5/lpmud.log 2>&1
    if [ $? -eq 2 ]; then break; fi
done > /dev/null 2>&1
