#!expect --
# Synopsis: fixcat
# Author: Don Libes

# Description: test to see if /bin/cat is unbuffered (i.e., -u is needed)
# Return 0 if buffered, 1 if unbuffered.
#
# If this file is sitting in an architecture-specific library directory,
# then it serves as a marker that your /bin/cat buffers by default.

log_user 0
spawn /bin/cat
send "\r"
expect "\r\n\r\n" {exit 1}
