'\"
'\" Copyright 1992 Regents of the University of California
'\" Permission to use, copy, modify, and distribute this
'\" documentation for any purpose and without fee is hereby
'\" granted, provided that this notice appears in all copies.
'\" The University of California makes no representations about
'\" the suitability of this material for any purpose.  It is
'\" provided "as is" without express or implied warranty.
'\" 
'\" $Header: /a/cvs/386BSD/ports/x11/tk/doc/ClrSelect.3,v 1.1 1993/08/09 01:20:58 jkh Exp $ SPRITE (Berkeley)
'\" 
.so man.macros
.HS Tk_ClearSelection tk
.BS
.SH NAME
Tk_ClearSelection \- Deselect the selection
.SH SYNOPSIS
.nf
\fB#include <tk.h>\fR
.sp
\fBTk_ClearSelection\fR(\fItkwin\fR)
.SH ARGUMENTS
.AS Tk_Window tkwin
.AP Tk_Window tkwin in
The selection will be cleared from the display containing this
window.
.BE

.SH DESCRIPTION
.PP
\fBTk_ClearSelection\fR cancels the selection for the display
containing \fItkwin\fR.
The selection need not be in \fItkwin\fR itself or even in
\fItkwin\fR's application.
If there is a window anywhere on \fItkwin\fR's display that
owns the primary selection, the window will be notified and the
selection will be cleared.
If there is no primary selection on the display, then the
procedure has no effect.

.SH KEYWORDS
clear, selection
