'\"
'\" Copyright 1990 Regents of the University of California
'\" Permission to use, copy, modify, and distribute this
'\" documentation for any purpose and without fee is hereby
'\" granted, provided that this notice appears in all copies.
'\" The University of California makes no representations about
'\" the suitability of this material for any purpose.  It is
'\" provided "as is" without express or implied warranty.
'\" 
'\" $Header: /a/cvs/386BSD/ports/x11/tk/doc/Sleep.3,v 1.1 1993/08/09 01:21:02 jkh Exp $ SPRITE (Berkeley)
'\" 
.so man.macros
.HS Tk_Sleep tk
.BS
.SH NAME
Tk_Sleep \- delay execution for a given number of milliseconds
.SH SYNOPSIS
.nf
\fB#include <tk.h>\fR
.sp
\fBTk_Sleep\fR(\fIms\fR)
.SH ARGUMENTS
.AP int ms in
Number of milliseconds to sleep.
.BE

.SH DESCRIPTION
.PP
This procedure delays the calling process by the number of
milliseconds given by the \fIms\fR parameter, and returns
after that time has elapsed.  It is typically used for things
like flashing a button, where the delay is short and the
application needn't do anything while it waits.  For longer
delays where the application needs to respond to other events
during the delay, the procedure \fBTk_CreateTimerHandler\fR
should be used instead of \fBTk_Sleep\fR.

.SH KEYWORDS
sleep, time, wait
