.TH LINKDATA 1 "version 0.59, June 4, 1990"
.SH NAME
linkdata \- link ML-object (`.mo') files into an a.out format (`.o') file.
.SH SYNOPSIS
.B linkdata
file1 file2 ...
.br
.SH DESCRIPTION
.PP
.IR linkdata
reads the named ML-object files (suffixed with `.mo'), and produces a standard
`.o' file named `allmo.o.'
This is used by \fBmakeml\fP to link the ML modules into the text segment of the
SML/NJ system.
.SH "SEE ALSO"
makeml(1)
