.TH SML 1 "version 0.75, November 8, 1991"
.SH NAME
sml, smld, smlc \(mi Standard ML compiler
.SH SYNOPSIS
.B sml
[
.I options
]
.br
.B smld
[
.I options
]
.br
.B smlc
.br
.SH DESCRIPTION
.I sml
is the Standard ML of New Jersey compiler.
It is an incremental, interactive compiler and accepts declarations and expressions
to be evaluated from standard input.
While there are no standard command line options, the command line arguments
are available to ML programs by calling the function
.RS .5i
System.argv : unit -> string
.RE
The Unix environment variables can be obtained by calling the function
.RS .5i
System.environ : unit -> string list
.RE
.PP
.I smld
is a version of the interactive system with the debugger loaded.
.PP
.I smlc
is the batch compiler.
This is normally used for compiling the compiler.
.SH "SEE ALSO"
makeml(1)
.br
Robert Harper, Robin Milner, and Mads Tofte,
`The Definition of Standard ML',
MIT Press.
.br
L.C. Paulson, ``ML for the Working Programmer,'' Cambridge Univ. Press.
.br
Andrew P. Tolmach and Adam T. Dingle, ``Debugging in Standard ML of New Jersey.''
.SH DIAGNOSTICS
The diagnostics produced by
.I sml
itself are intended to be self-explanatory.
