#! /bin/sh
# Find size of current queue of news outbound to $1.  Old-uucp version.

# =()<. ${NEWSCONFIG-@<NEWSCONFIG>@}>()=
. ${NEWSCONFIG-/usr/lib/news/bin/config}

PATH=$NEWSCTL/bin:$NEWSBIN:$NEWSPATH ; export PATH
umask $NEWSUMASK

cd /usr/spool/uucp
grade=d

case "$1" in
?|??|???|????|?????|??????|???????)	site="$1" ;;
*)	site=`expr "$1" : '^\(.......\).*'`
esac

if test -d C.
then
	cd C.
	ls | egrep "^C\.$site$grade....\$" | wc -l
else
	echo 0
fi
