.TH VFTOVP 1 8/15/90
.SH NAME
vftovp - convert virtual font (vf) files to virtual property list format
.SH SYNOPSIS
.B vftovp
vf_file_name tfm_file_name vpl_file_name
.SH DESCRIPTION
The 
.I vftovp
program translates a (program-oriented) virtual font file and its
accompanying font metric file to a (human-oriented) property list file.
Thus, the virtual font can be edited, and its exact contents can be
displayed mnemonically.  It also serves as a VF-file validating program;
if no error messages are given, the input files are correct.
.PP
The
.I vpl_file_name,
must be complete. No adding of default extensions is done.  The
.I vf_file_name
is searched for using the VFFONTS environment variable.  If VFFONTS is
not set, the system default is used:
.BR @TEXFONTS@ .
The
.I tfm_file_name
is searched for using the TEXFONTS environment variable; the default is
the same.
See
.BR tex (1)
for the details of the searching.
.SH AUTHORS
Donald Knuth wrote the program, based in part on an idea of David Fuchs,
starting with the code for
.BR tftopl (1).
Karl Berry originally ported it to Unix.
