#!/bin/sh
# -*- Mode: Text;  -*-
# File: DEFSITE
# Author: Heinz Schmidt (hws@csis.dit.csiro.AU)
# Copyright (C) CSIRO Division of Information Technology, 1993
#
#*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#* FUNCTION: configuration file to edit or overwrite by command line
#*           options to the "configure" command.
#*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# The build directory, by default ../
TOPDIR=@TOPDIR@

# The ultimate location of your Sather installation, by default $TOPDIR
SATHER_HOME=@SATHER_HOME@

# The file  make/${ARCH}${CLANG} must select compiler switches and binaries
# will end up in bin.${ARCH}${CLANG}

# An architecture symbol known to the current system, guessed by default.
ARCH=`./arch.guess`

# The C language you use "kr" or "ANSI", by default ANSI if gcc is around, else kr
CLANG=@CLANG@

# The group of the build and install directories will be this.
SATHERGRP=sather

# The make facility to use.
SATHER_MAKE=make

# For passing data from Sather to C the sac auxiliaries may be handy.
SKIPSAC=NO
