.TH DVITYPE 1L  10/16/86
.SH NAME
dvitype - translate a dvi file for humans to read
.SH SYNOPSIS
.B dvitype
dvi_file_name
.SH DESCRIPTION
.I Dvitype
translates a dvi (DeVice Independent) file (output by TeX) to a
file humans can read. It also serves as a dvi file-validating
program (i.e., if
.I dvitype
can read it, it's correct) and as an example of a dvi-reading
program for future device drivers.
.PP
The output file can include all commands, just the important
ones, or none at all (in which case only errors are reported).
Only certain pages may be selected for transliteration, the
magnification and resolution of the ``output device'' may be
changed, and so on. All options are specified with an on-line dialogue.
.PP
The dvi filename on the command line must be complete. The
.I .dvi
extension is not supplied if omitted. The output always goes
to
.IR dvitype.out .
.SH "SEE ALSO"
gftype(1), tex(1), lpr(1)
.br
Donald Knuth,
.I TeXware
.SH "AUTHORS"
Donald Knuth wrote the program. It was published as
part of the
.I TeXware
technical report, available from Stanford. Howard Trickey
and Pavel Curtis ported it to Unix.
