.TH GFTOPK 1L  9/19/88
.SH NAME
gftopk - convert generic font files to packed font files
.SH SYNOPSIS
.B gftopk
[-v] gf_file_name [pk_file_name]
.SH DESCRIPTION
.I Gftopk
converts a generic font file (output by Metafont) to a
packed font file for use by dvi-reading programs. Packed
font files are much smaller than the corresponding gf files,
and it is rapidly becoming the font format of choice.
.PP
The gf filename on the command line must be complete. Because
the resolution is part of the extension, it would not make
sense to add on a default extension as is done with TeX or
dvi-reading software. The pk file name defaults to the same
stripped name as the gf file, and it is placed in the current
working directory with the `pk' extension replacing `gf'. For
example, the input file
.I io.300gf
would become
.IR io.300pk .
.PP
Unless the gf filename begins with a / (absolute path), gftopk will 
search the environment variable 
.B GFFONTS
for an input directory path, and will default to the
.B TEXFONTS
directory path if 
.B GFFONTS 
does not exist.  It runs absolutely
silently, unless the 
.I -v
flag is set.
.SH "SEE ALSO"
mf(1), lpr(1)
.br
Donald Knuth,
.I MetafontWare
.SH "AUTHORS"
Tomas Rokicki wrote the program. The program was published as
part of the
.I MetafontWare
technical report, available from Stanford. Pierre MacKay
adapted it for compilation under web2c.
