.TH GFTYPE 1L  10/6/88
.SH NAME
gftype - translate a generic font file for humans to read
.SH SYNTAX
.B gftype
[\|\fIoptions\fR\|] gf_file_name [output_file_name]
.SH DESCRIPTION
.PN Gftype
translates a \fIgeneric font\fR file (output by Metafont) to a
file humans can read. It also serves as a \fIgf\fR file-validating
program (i.e., if
.PN gftype
can read it, it's correct) and as an example of a \fIgf\fR\|-reading
program for conversion programs.
.PP
The \fIgf\fR filename on the command line must be complete. Because
the resolution is part of the extension, it would not make
sense to add on a default extension as is done with TeX or
dvi-reading software. All output is to standard output.
.SH "OPTIONS"
The output file can include a symbolic listing of the \fIgf\fR commands,
and/or bit-map images of the characters
(which makes it a lot longer).
Both options are specified by command line switches.
.IP \fB-m\fR 0.3i
Displays the symbolic listing of commands (mnemonics).
.IP \fB-i\fR 0.3i
Displays the bit-map of each character.
.SH "SEE ALSO"
dvitype(1), mf(1), lpr(1)
.br
Donald Knuth,
.I MetafontWare
.SH "AUTHORS"
David Fuchs wrote the program. The program was published as
part of the
.I MetafontWare
technical report, available from Stanford. Pierre MacKay
ported it to Unix for WEB-to-C.
