.TH PKTOGF 1L  9/19/88
.SH NAME
pktogf - convert packed font files to generic font files
.SH SYNOPSIS
.B pktogf
[-v] pk_file_name [gf_file_name]
.SH DESCRIPTION
.I Gftopk
converts a packed font file back to a
generic font file for use by dvi-reading programs. Packed
font files are much smaller than the corresponding gf files,
but many devices use generic font files.
.PP
The pk filename on the command line must be complete. Because
the resolution is part of the extension, it would not make
sense to add on a default extension as is done with TeX or
dvi-reading software. The gf file name defaults to the same
stripped name as the pk file, and it is placed in the current
working directory with the `gf' extension replacing `pk'. For
example, the input file
.I io.300pk
would become
.IR io.300gf .
.PP
Unless the pk filename begins with a / (absolute path), pktogf will search 
the environment variable 
.B PKFONTS
for an input directory path, and will default to the
.B TEXFONTS
directory path if 
.B PKFONTS 
does not exist.  It runs absolutely
silently, unless the 
.I -v
flag is set.
.SH "SEE ALSO"
mf(1), lpr(1)
.br
Donald Knuth,
.I MetafontWare
.SH "AUTHORS"
Tomas Rokicki wrote the program.  Pierre MacKay
adapted it for compilation under web2c.
