.TH PKTYPE 1L  10/16/86
.SH NAME
pktype - translate a packed font file for humans to read
.SH SYNOPSIS
.B pktype
pk_file_name [output_file_name]
.SH DESCRIPTION
.I Pktype
translates a packed font file to a
file humans can read. It also serves as a pk file-validating
program (i.e., if
.I pktype
can read it, it's correct) and as an example of a pk-reading
program for device drivers and future conversion programs.
.PP
The output file includes information about the widths,
heights, and other assorted statistics about the characters.
.PP
The pk filename on the command line must be complete. Because
the resolution is part of the extension, it would not make
sense to add on a default extension as is done with TeX or
dvi-reading software. If the
.I output_file_name
is not specified, standard output is used.
.SH "SEE ALSO"
gftype(1)
.br
Donald Knuth,
.I MetafontWare
.SH "AUTHORS"
Tomas Rokicki wrote the program. The program was published as
part of the
.I MetafontWare
technical report, available from Stanford. Paul Richards
ported it to Unix.
