.TH PLTOTF 1L  10/16/86
.SH NAME
pltotf - convert property list files to font metric (tfm)
.SH SYNOPSIS
.B pltotf
pl_file_name tfm_file_name
.SH DESCRIPTION
.I Pltotf
translates a (human-readable) property list file to a
(program-readable) font metric file. Thus, the font metric
file can be edited (although this should not be necessary
since Metafont84 has been released), and its exact contents
displayed mnemonically.
.PP
Both the
.I pl_file_name
and the
.I tfm_file_name
must be complete. No adding of default extensions is done.
.SH "SEE ALSO"
chtopx(1)
.br
Donald Knuth,
.I TeXware, The Metafontbook
.SH "AUTHORS"
Donald Knuth wrote the program. It was published as
part of the
.I TeXware
technical report, available from Stanford. Howard Trickey,
Pavel Curtis, and Richard Furuta ported it to Unix.
