.TH TFTOPL 1L  10/16/86
.SH NAME
tftopl - convert font metric (tfm) files to property list
.SH SYNOPSIS
.B tftopl
tfm_file_name pl_file_name
.SH DESCRIPTION
.I Tftopl
translates a (program-readable) font metric file to
a (human-readable) property list file. Thus, the font metric
file can be edited (although this should not be necessary
since Metafont84 has been released), and its exact contents
displayed mnemonically.
.I Tftopl
also serves as a tfm file validating program.
.PP
Both the
.I tfm_file_name
and the
.I pl_file_name
must be complete. No adding of default extensions is done.
.SH "SEE ALSO"
pxtoch(1)
.br
Donald Knuth,
.I TeXware, The Metafontbook
.SH "AUTHORS"
Donald Knuth wrote the program. It was published as
part of the
.I TeXware
technical report, available from Stanford. Howard Trickey and
Pavel Curtis ported it to Unix.
