#! /bin/csh -f
# Update /etc/shell on deinstallation
        echo "updating /etc/shells"
        cp /etc/shells /etc/shells.bak
        (grep -v /usr/local/bin/ksh /etc/shells.bak) \
                > /etc/shells

