#! /bin/csh -f
# Update /etc/shells on post install

if($1 == "ksh_bin") then
if($2 == "POST-INSTALL") then
        echo "updating /etc/shells"
        cp /etc/shells /etc/shells.bak
        (grep -v /usr/local/bin/ksh /etc/shells.bak; echo /usr/local/bin/ksh) \
                > /etc/shells
endif
else
echo "Package name is not ksh_bin, this script only works for ksh_bin"
endif
