@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@node Built-in Functions, Invoking Octave, Built-in Variables, Top
@chapter Built-in Functions
@cindex Functions
@cindex built-in functions
@cindex functions, built-in

@menu
* Matrix Manipulation::         
* Utility Functions::           
* Complex Arithmetic::          
* Trigonometry::                
* Plotting::                    
* Linear Algebra::              
* Nonlinear Equations::         
* Differential Equations::      
* Optimization::                
* Quadrature::                  
* Signal Processing::           
* Input and Output::            
* Special Matrices::            
* Statistics::                  
* String Functions::            
* Time and Date::               
* Inquiry Functions::           
* Everything Else::             
@end menu

