@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@node Introduction, Expressions, Acknowledgements, Top
@chapter A Brief Introduction to Octave
@cindex introduction

This manual will eventually document how to run, install and port
Octave, and how to report bugs.

This document corresponds to Octave version 0.74.

@c XXX FIXME XXX -- add explanation about how and why Octave was written.
@c
@c XXX FIXME XXX -- add a sentence or two explaining that we could
@c                  always use more funding.

@menu
* Getting Started::             
* Running Octave::              
* Simple Examples::             
@end menu

@node Getting Started, Running Octave,  , Introduction
@section Getting Started
@cindex getting started

@node Running Octave, Simple Examples, Getting Started, Introduction
@section Running Octave

@node Simple Examples,  , Running Octave, Introduction
@section Simple Examples

@c should have examples of the following, with M-files for the examples
@c provided somewhere in the distribution
@c
@c matrix multiply
@c solution of linear equations
@c svd
@c solution of differential equations
@c graphics
