@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@node Invoking Octave, Command Line Editing, Built-in Functions, Top
@chapter Octave Command Options
@cindex Octave command options
@cindex command options
@cindex options, Octave command

@table @code
@item -d
Enter parser debugging mode.

@item -f
Don't read any of the system or user initialization files at startup.

@item -h
@item -?
Print short help message and exit.

@item -i
Force interactive behavior.

@item -p @var{path}
Specify the path to search for M-files.  The value of @var{path}
specified on the command line will override any value of
@samp{OCTAVE_PATH} found in the environment, but not any
@samp{LOADPATH = "path"} commands found in the system or user startup
files.

@item -q
Don't print message at startup.

@item -v
Print the program version number and exit.

@item -x
Echo commands as they are executed.

@item @var{file}
Execute commands from @var{file}.
@end table
