\input texinfo  @c -*-texinfo-*-
@setfilename octave.info

@c @smallbook
@c @setchapternewpage odd
@c @cropmarks
@c @finalout

@iftex
@set DONTINCLUDEGPL
@end iftex

@settitle Octave

@ifinfo

Copyright (C) 1993 John W. Eaton.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through Tex and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of
this manual under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of
a permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for
modified versions.
@end ifinfo

@titlepage
@title{Octave}
@subtitle{A high-level interactive language for numerical computations}
@c
@c ***********************************************************
@c *** The version number appears twice more in this file, ***
@c *** and again in the file intro.texi                    ***
@c ***********************************************************
@c
@subtitle{Edition 1.0 for Octave version 0.74}
@subtitle{June 1993}
@author{John W. Eaton}
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1993 John W. Eaton.

This is the first edition of the Octave documentation,
and is consistent with version 0.74 of Octave.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the same conditions as for modified versions.
@end titlepage

@ifinfo
@node Top, Acknowledgements, (dir), (dir)
@top

This manual documents how to run, install and port Octave, as well as
its new features and incompatibilities, and how to report bugs.
It corresponds to Octave version 0.74.
@end ifinfo

@menu
* Acknowledgements::            Thanks.
* Introduction::                A brief introduction to Octave.
* Expressions::                 Expressions.
* Statements::                  Looping and program flow control.
* Built-in Variables::          Descriptions of all built-in variables.
* Built-in Functions::          Descriptions of all built-in functions.
* Invoking Octave::             Command options supported by Octave.
* Command Line Editing::        Command history and editing.
* Installation::                How to configure, compile and install Octave.
* Trouble::                     If you have trouble installing Octave.
* Concept Index::               An item for each concept.
* Variable Index::              An item for each documented variable.
* Function Index::              An item for each documented function.

 --- The Detailed Node Listing ---

Acknowledgements

* Contributors::                People who contributed to developing of Octave.

A Brief Introduction to Octave

* Getting Started::             
* Running Octave::              
* Simple Examples::             

Expressions

* Constant Expressions::        
* Matrices::                    
* Ranges::                      
* Variables::                   
* Index Expressions::           
* Calling Functions::           
* Global Variables::            
* Keywords::                    
* Arithmetic Ops::              
* Comparison Ops::              
* Boolean Expressions::         
* Assignment Ops::              
* Increment Ops::               
* Operator Precedence::         

Statements

* Statement Lists::             
* Declaration Statements::      
* Selection Statements::        
* Iteration Statements::        
* Defining Functions::          
* Jump Statements::             

Command Line Editing

* Introduction and Notation::   Notation used in this text.
* Readline Interaction::        The minimum set of commands for editing a line.
* Readline Init File::          Customizing Readline from a user's view.

Readline Interaction

* Readline Bare Essentials::    The least you need to know about Readline.
* Readline Movement Commands::  Moving about the input line.
* Readline Killing Commands::   How to delete text, and how to get it back!
* Readline Arguments::          Giving numeric arguments to commands.

Readline Init File

* Readline Init Syntax::        Syntax for the commands in @file{~/.inputrc}.
* Readline Vi Mode::            Switching to @code{vi} mode in Readline.

Readline Init Syntax

* Commands For Moving::         Moving about the line.
* Commands For History::        Getting at previous lines.
* Commands For Text::           Commands for changing text.
* Commands For Killing::        Commands for killing and yanking.
* Numeric Arguments::           Specifying numeric arguments, repeat counts.
* Commands For Completion::     Getting Readline to do the typing for you.
* Miscellaneous Commands::      Other miscellaneous commands.

Installing Octave

* Binary Distributions::        

Binary Distributions

* Installing Octave from a Binary Distribution::  
* Creating a Binary Distribution::  

Known Causes of Trouble with Octave

* Actual Bugs::                 Bugs we will fix later.
* Installation Problems::       Problems that manifest when you install Octave.
* Disappointments::             Regrettable things we can't change.
* Reporting Bugs::              
* Bug Criteria::                
* Bug Lists::                   
* Bug Reporting::               
* Sending Patches::             
* Service::                     

Reporting Bugs

* Bug Criteria::                
* Where: Bug Lists.             Where to send your bug report.
* Reporting: Bug Reporting.     How to report a bug effectively.
* Patches: Sending Patches.     How to send a patch for Octave.
@end menu

@include ack.texi

@include intro.texi

@include expr.texi

@include stmt.texi

@include var.texi

@include fcn.texi

@include invoke.texi

@include rluser.texi

@include install.texi

@include bugs.texi

@include cp-idx.texi

@include vr-idx.texi

@include fn-idx.texi

@contents

@bye
