@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@node Signal Processing, Statistics, Control Theory, Top
@chapter Signal Processing

I hope that someday Octave will include more signal processing
functions.  If you would like to help improve Octave in this area,
please contact @code{bug-octave@@che.utexas.edu}.

@ftable @code
@item fft (@var{a})
Compute the FFT of @var{a} using subroutines from FFTPACK.

@item ifft (@var{a})
Compute the inverse FFT of @var{a} using subroutines from FFTPACK.
@end ftable
