@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@node Statistics, Plotting, Signal Processing, Top
@chapter Statistics

I hope that someday Octave will include more statistics functions.  If
you would like to help improve Octave in this area, please contact
@code{bug-octave@@che.utexas.edu}.

@ftable @code
@item mean (@var{a})
If @var{a} is a vector, compute the mean of the elements of @var{a}.  If
@var{a} is a matrix, compute the mean for each column and return them in
a row vector.

@item median (@var{a})
If @var{a} is a vector, compute the median value of the elements of
@var{a}.  If @var{a} is a matrix, compute the median value for each
column and return them in a row vector.

@item std (@var{a})
If @var{a} is a vector, compute the standard deviation of the elements
of @var{a}.  If @var{a} is a matrix, compute the standard deviation for
each column and return them in a row vector.
@end ftable
