@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@cindex strings

@node String Functions, System Utilities, Matrix Manipulation, Top
@chapter String Functions

Octave currently has a limited ability to work with strings.  There are
plans to improve this, but there are many other more important things to
be done first.

@findex strcmp

The function @code{strcmp (@var{s1}, @var{s2})} compares two strings,
returning 1 if they are the same, and 0 otherwise.

@strong{Note: For compatibility with @sc{matlab}, Octave's strcmp
function returns 1 if the strings are equal, and 0 otherwise.  This is
just the opposite of the corresponding C library function.}

@findex int2str
@findex num2str

The functions @code{int2str} and @code{num2str} convert a numeric
argument to a string.  These functions are not very flexible, but are
provided for compatibility with @sc{matlab}.  For better control over
the results, use @code{sprintf} (@pxref{Formatted Output}).

@findex setstr

The function @code{setstr} can be used to convert a vector to a string.
Each element of the vector is converted to the corresponding ASCII
character.  For example,

@example
setstr ([97, 98, 99])
@end example

@noindent
creates the string

@example
abc
@end example
