@c Copyright (C) 1992 John W. Eaton
@c This is part of the Octave manual.
@c For copying conditions, see the file gpl.texi.

@node Using Octave, Variables, Invoking Octave, Top
@chapter Using Octave

@menu
* Typing Commands::             
@end menu

@node Typing Commands, Typing Commands,  , Using Octave
@section Typing Commands

