#!/bin/sh
# 
# The file `mfbook.tex' is Copyrighted and cannot be modified.
# Please only use this script to satisfy your curiousity - not 
# to break the law.

ed - mfbook.tex <<\EOF
/iftrue/s//iffalse/
/pausing1/s//pausing0/
w mfbook.ill
q
EOF
