#
# makefile for sattrack/readelements package
#

CFLAGS+= -I../include 
BINDIR = /usr/local/sattrack
MAN1 =

PROG = readelements
SRCS = readelements.c calendar.c monthname.c readnorad.c

.include <bsd.prog.mk>
