/* sccsdata.c - sccs data file for Men3wn generated by mksccs */

char Men3wn_sccsdata_c_sccsid[] = "@(#)sccsdata.c	1.28 20/5/92";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  wdbyte.c: Add #include of <sys/types.h> for size_t.
 */

const char *_Men3wn_sccsdata[] = {
	"Men3wn version 1.28 (build date: Wed May 20 20:59:13 BST 1992)",
	"@{$Men3wn$}: sccsdata.c 1.28 ",
	"@{$Men3wn$}: marea.c 1.7 ",
	"@{$Men3wn$}: mclose.c 1.7 ",
	"@{$Men3wn$}: mcreate.c 1.10 ",
	"@{$Men3wn$}: mdisplay.c 1.12 ",
	"@{$Men3wn$}: mdup.c 1.9 ",
	"@{$Men3wn$}: mfmodes.c 1.6 ",
	"@{$Men3wn$}: minfo.c 1.6 ",
	"@{$Men3wn$}: minsert.c 1.10 ",
	"@{$Men3wn$}: mnewcap.c 1.8 ",
	"@{$Men3wn$}: mopen.c 1.12 ",
	"@{$Men3wn$}: mperror.c 1.6 ",
	"@{$Men3wn$}: msize.c 1.8 ",
	"@{$Men3wn$}: mstdfont.c 1.6 ",
	"@{$Men3wn$}: wdbyte.c 1.9 ",
	"@{$Men3wn$}: menu3.h 1.11 ",
	"@{$Men3wn$}: menu_priv.h 1.5 ",
	"@{$Men3wn$}: sccsdata.h 1.1 ",
	"@{$Men3wn$}: wdbyte.h 1.4 ",
	"@{$Men3wn$}: Makefile 1.11 ",
};
