.TH CLOSEALL 3 local
.DA 9 Feb 1982
.SH NAME
closeall \- close all files
.SH SYNOPSIS
.ft B
closeall(leavestd)
.br
int leavestd;
.ft R
.SH DESCRIPTION
.I Closeall
closes all currently-open file descriptors.
If
.I leavestd
is non-zero,
the standard input, output, and diagnostic descriptors are left open;
otherwise they are closed too.
.SH SEE ALSO
close(2), standard(3)
.SH HISTORY
Local invention.
.SH BUGS
Nothing wrong with
.IR closeall ,
but there ought to be an
.IR fcloseall .
