.TH EFOPEN 3 local
.DA 24 April 1984
.SH NAME
efopen \- open a stream, checking for errors
.SH SYNOPSIS
.nf
.B FILE *
.B efopen(file, mode)
.B char *file;
.B char *mode;
.SH DESCRIPTION
.I Efopen
invokes
.IR fopen (3)
and checks the result for errors.
In the absence of errors, it returns the stream pointer;
in the presence of errors, it prints a message and exits.
.SH SEE ALSO
fopen(3), error(3)
.SH DIAGNOSTICS
Exit status, in the event of error, is 1.
.SH HISTORY
Local product, roughly following the one in Kernighan&Pike.
