/*
	Generated by IDL: 1.4 92/10/30 13:09:32
*/

#line 1 "[prologue--triv.idl]"
typedef  char*         string;
typedef  void          unit;
typedef  char*         address;
typedef  char          bool;
typedef  unsigned char byte;
extern   int  idlcontinue;
extern   void idlserver();
extern   void idlreset();
extern   string read_string();
extern   void write_string();
extern   int read_int();
extern   void write_int();
extern   short read_short();
extern   void write_short();
extern   address read_address();
extern   void write_address();

#line 1 "triv.idl"
#line 1

	typedef struct Wodget { int a; } Wodget;

#line 4
#define read_Widget (Widget) read_address
#define write_Widget write_address
typedef Wodget* Widget;

#line 5
#define read_Window (address) read_address
#define write_Window write_address

#line 6
#define read_Pos (Pos) read_short
#define write_Pos write_short
typedef short Pos;

#line 7
#define read_Dim (Dim) read_int
#define write_Dim write_int
typedef short Dim;

#line 8
#define read_String (char*) read_address
#define write_String write_address

#line 9
#define read_Str (Str) read_string
#define write_Str write_string
typedef char* Str;

#line 11
static void WidgetToWindow(a) Widget a;
{ write_Window(a);
}


#line 12
static void WidgetToDim(w) Widget w;
{ write_Dim(GetDim(w));
}


#line 14
static void WidgetToDimPos(w) Widget w;
{ 
	Dim d = GetDim(w);

write_Dim(d );write_Pos(GetPos(w, d));
}


#line 20

	/*  C Comment */

#line 24
static void WidgetToDimPos1(w) Widget w;
{ write_Dim(GetDim(w) );write_Pos(GetPos(w, 1));
}


#line 25
static void WidgetToDimPos2(w) Widget w;
{ write_Dim(GetDim(w) );write_Pos(GetPos(w, 2));
}


#line 26
static void Echo(s) char* s;
{ write_Str(s);
}


#line 27
static void EchoStr(s) Str s;
{ write_Str(s);
}


#line 29


static void GetSignature() 
{ write_string("WidgetToWindow:Widget->Window;WidgetToDim:Widget->Dim;WidgetToDimPos:Widget->Dim,Pos;WidgetToDimPos1:Widget->Dim,Pos;WidgetToDimPos2:Widget->Dim,Pos;Echo:String->Str;EchoStr:Str->Str;");
}


#line 1 "[epilogue--triv.idl]"
void idlevent()
{
 switch(read_int())
 {
   case 8: { Widget a = read_Widget(); WidgetToWindow(a); }; break;
   case 7: { Widget w = read_Widget(); WidgetToDim(w); }; break;
   case 6: { Widget w = read_Widget(); WidgetToDimPos(w); }; break;
   case 5: { Widget w = read_Widget(); WidgetToDimPos1(w); }; break;
   case 4: { Widget w = read_Widget(); WidgetToDimPos2(w); }; break;
   case 3: { char* s = read_String(); Echo(s); }; break;
   case 2: { Str s = read_Str(); EchoStr(s); }; break;
   case 1: { GetSignature(); }; break;
 };
 idlreset();
}
void idlserver() { while (idlcontinue) idlevent(); }
