%{
	typedef struct Wodget { int a; } Wodget;
%}
typedef Widget = Wodget* => address;
type    Window = address;
typedef Pos    = short;
typedef Dim    = short  => int;
type    String = char*  => address;
typedef    Str = char*  => string;

WidgetToWindow(a:Widget) : Window    => a
WidgetToDim(w:Widget)    : Dim       => GetDim(w)

WidgetToDimPos(w:Widget) : Dim*Pos =
%{
	Dim d = GetDim(w);

%}      => d => GetPos(w, d);

%{
	/*  C Comment */
%}

WidgetToDimPos1(w:Widget) : Dim Pos => GetDim(w) => GetPos(w, 1);
WidgetToDimPos2(w:Widget) : Dim Pos => GetDim(w) ,  GetPos(w, 2);
Echo(s: String) : Str => s
EchoStr(s: Str) : Str => s

${
	fun StartServer args =
	(idlbase.startserver "foo" args;
	 if GetSignature() = Signature then
	    (outputc std_err "[Wrong server]\n";
	     raise Interrupt
	    )
	 else

	)
$}
