XBoing Installation
===================

Updated: 2nd November 1993

Requirements
------------

- You must be using X11R4 or X11R5. It may work on X11R3 but cannot test it!
- You must have the XPM pixmap library. The XPM library can be obtained from
  the following sites:-

  avahi.inria.fr (138.96.24.30)     - Latest revision. (Europe)     V3.2g
    - in /pub/xpm
  ftp.x.org (198.112.44.100)        - Latest revision. (America)    V3.2g
    - in /contrib
  archie.au (139.130.4.6)           - Latest revision. (Australia)  V3.2g
    - in /X11/contrib

  The author of XPM is lehors@sophia.inria.fr - BULL Research FRANCE 
  I suggest you use 3.2g as it has had the best reports. 3.2f may have some
  problems but works for me!

- v1.7 has now been compiled and I've be told  works on the following machines,

    + SunOS 4.1.2 5 sun4c/sun4m
    + SunOS Solaris 2.2 LX
    + IRIX 4.0.5G 12171207 IP7
    + SGI 310/GTX
    + HP 9000/720 HP-UX 8.07
    + DEC 2100
    + Coherent on i486/386!
    + NCR 3000
    + DEC OSF/1 AXP
    + DECstation 5000/133 ULTRIX 4.2/4.3 0 RISC
    + AIX 3.2.3e rs6000/350
    + NetBSD on i486
    + Linux on i486.
    + Intel 486 ESIX 4.0.4 X11R4

- You must have a COLOUR display. Sorry to all those B&W dudes. I'll look 
  into greyscale, but not likely.

- An ANSI compiler would be nicer however I spent ages changing code with
  all those lovely #ifdefs so you can use a non-ansi compiler. :-)

- This game DOES NOT need Motif or Xt or anything except pure XLib.

- The xnews Sun X server is NOT the quickest with this game. Be warned.


Makefiles
---------

Included in this package is an Imakefile which generates a Makefile that will
compile XBoing using your system setup. For those people without imake, or
who can't get it to compile, a Makefile.std is also included. 


Compilation
-----------

Edit the Imakefile or the Makefile.std and change the default compiler to
your compiler. Also change the compiler flags if necessary. 

Change the $(XBOING_DIR) to point to the place where xboing is to be 
installed. In that directory xboing will create the highscore file and also
place the level data and sound data.

NOTE: The user can now specify the sounds, level and highscore file locations
      as environment variables. They are :-

XBOING_SCORE_FILE = the highscore file to be used.
XBOING_LEVELS_DIR = the directory containing the levels.
XBOING_SOUND_DIR  = the directory containing the sounds.

On some machines the file locking may not be available or work. Please try and
if you get errors then set the NO_LOCKING define on or turn on USE_FLOCK and
see if you have that. This is relevant to the highscore file locking so it
is not major if only a few people are playing the game. Linux dudes need to set
USE_FLOCK I am told.

Also set the AUDIO_AVAILABLE flag to True or False to enable the audio in
the game if possible. You may want to disable audio for everyone even if it
is available. ie: universities.

Check the audio directory and see if audio is supported by xboing. Then check
the Imakefile and see if it will automatically use the correct audio source.
If not then change the default NOaudio.c to the one you want. For NCD & RPLAY
users that's what you'll have to do. Don't forget to set the AUDIO_LIB and the
AUDIO_INCLUDE variables.

    LINUXaudio.c    - SoundBlaster support on Linux for PC.
    RPLAYaudio.c    - Support for the rplay sound system.
    SUNaudio.c      - Sun workstation audio 
    NCDaudio.c      - NCD X terminal NCDaudio support. See below.
    HPaudio.c       - HP audio which is .au format?
    NOaudio.c       - Default - no audio support file.
	AFaudio.c       - Audiofile sound server. See below.

The default will be no audio at all. ie: NOaudio.c


Audiofile Sound Server
----------------------

Also, the Imakefile needs an "-lAF -lAFUtil" added to it for AudioFile.
-I<audiofileroot>/AF/AFlib.h -L<audiofileroot>/AF/lib


NCD Audio Server or NetAudio
----------------------------

Needs -laudio -L<ncdaudiolibdir> -I<ncdincludedir>

Rplay sound system
------------------

?



Please work on NOaudio.c if you have another machine that you want to post
the sound too. Note that I am not going to support and other file format than
.au as I'll have sound files everywhere. :-)

**************************************************************************
See the troubleshooting bit near the end of the doco if you have problems.
**************************************************************************

If you have imake, type:

    xmkmf
    make depend
    make all

X11R5 users can type 'xmkmf -a ; make all' if they like.

If you do not have imake, type:

    cp Makefile.std Makefile
    make depend
    make all


Installation
------------

Try 'xboing -setup' and see if the compilation has gone as you planned.
This option will print out useful information about where xboing will look
for its data files.

Please note that you must be root to install the game. If you are not root
then you can just run XBoing from your own account.

Don't forget to set the $(XBOING_DIR) in the Makefile/Imakefile and re-compile
if you don't like where it will be installed.

For imake users, type:

    make install             - install XBoing binary.
    make install.man         - install the manual page.

If you do not have imake then you must first edit the Makefile.std to check
that where you want the program to be installed.

    make install             - install XBoing binary.
    make install.man         - install the manual page.
    
You should now have XBoing installed and it's manual page. If not, then please
read README.problems.


HighScore File
--------------

It is automatically created and chmoded to 0666. There will also be a personal
highscore file saved in each users account home directory. This keeps their
personal highscores. If you have problems then touch one and chmod it to
something that will work for you. ie: rw for all.

Global file is different as it now only contains one entry per person. ie:
their highest score.

NOTE: **** The highscore file format has changed since v1.6. Any old ones 
           will barf! Global files have one entry now. Just erase them please.

Copyright
---------

XBoing: 

/*****************************************************************************
 
          (c) Copyright 1993, Justin C. Kibell, All Rights Reserved
                           email: jck@citri.edu.au

  Permission to use, copy, modify, and distribute this software and its
  documentation without written agreement is hereby granted. You cannot sell 
  this software without written permission from the author. This entire 
  copyright notice must appear in all copies of this software.

  IN NO EVENT SHALL THE AUTHOR BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, 
  SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF 
  THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE AUTHOR HAS BEEN ADVISED 
  OF THE POSSIBILITY OF SUCH DAMAGE.

  THE AUTHOR SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED 
  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
  PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE 
  AUTHOR HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, 
  ENHANCEMENTS, OR MODIFICATIONS.

 *****************************************************************************/

Xpm:
  ----------------------------------------------------------------------------
/*
 * Copyright 1990-93 GROUPE BULL
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose and without fee is hereby granted, provided
 * that the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the name of GROUPE BULL not be used in advertising
 * or publicity pertaining to distribution of the software without specific,
 * written prior permission.  GROUPE BULL makes no representations about the
 * suitability of this software for any purpose.  It is provided "as is"
 * without express or implied warranty.
 *
 * GROUPE BULL disclaims all warranties with regard to this software,
 * including all implied warranties of merchantability and fitness,
 * in no event shall GROUPE BULL be liable for any special,
 * indirect or consequential damages or any damages
 * whatsoever resulting from loss of use, data or profits,
 * whether in an action of contract, negligence or other tortious
 * action, arising out of or in connection with the use
 * or performance of this software.
 *
 */

Arnaud LE HORS      BULL Research FRANCE -- Koala Project
                    (XPM - X PixMap format version 2 & 3)
    Internet:       lehors@sophia.inria.fr
Surface Mail:       Arnaud LE HORS, INRIA - Sophia Antipolis,
                    2004, route des Lucioles, 06565 Valbonne Cedex -- FRANCE
 Voice phone:       (33) 93.65.77.71, Fax: (33) 93 65 77 66, Telex: 97 00 50 F
  ----------------------------------------------------------------------------

-------------------------------------------------------------------------------
Justin Kibell - jck@citri.edu.au - +61 3 282 2456 - Vic - Australia
