#!/bin/sh
# printmail: part of the Elm mail system
# @(#)$Id: printmail,v 1.3 1993/08/27 00:57:31 smace Exp $
#		Copyright (c) 1988-1992 USENET Community Trust
# 		Copyright (c) 1986,1987 Dave Taylor
 
if [ "$1" = "-p" ]; then
  flags="-p";shift
fi
 
if [ "$1" != "" ]; then
  if [ ! -r $1 ]; then
    echo printmail: cannot open folder $1 1>&2
    exit 1
  else
    flags="$flags -f $1"
  fi
fi
 
# and now invoke readmsg
exec readmsg $flags \*
