#
# Tests for indexing operations
#

set test index-setup
send "clear
do_fortran_indexing = \"false\";
a = \[\];\n"
expect {
	-re "$resync"	{ }
}

set test index-1
send "isempty (a)\n"
expect {
	-re "ans = 1$nl.*$prompt$"			{ pass "$test" }
}

set test index-2
send "a(1) = 1\n"
expect {
	-re "a = 1$nl.*$prompt$"			{ pass "$test" }
}

set test index-setup
send "do_fortran_indexing = \"true\";
a = \[\];\n"
expect {
	-re "$resync"	{ }
}

set test index-3
send "isempty (a)\n"
expect {
	-re "ans = 1$nl.*$prompt$"			{ pass "$test" }
}

set test index-4
send "a(1) = 1\n"
expect {
	-re "a = 1$nl.*$prompt$"			{ pass "$test" }
}
