#
# Tests for the transpose operator.
#

set test transpose-setup
send "clear
scalar = 2;
range = 1:4;
vector = \[1;2;3;4\];
matrix = \[1,2;3,4\];\n"
expect {
	-re "$resync"
}

set test transpose-1
send "scalar'\n"
expect {
	-re "ans = 2.*$prompt$"				{ pass "$test" }
}

set test transpose-2
send "range'\n"
expect {
  -re "ans = *$nl *1$nl *2$nl *3$nl *4.*$prompt$"	{ pass "$test" }
}

set test transpose-3
send "vector'\n"
expect {
	-re "ans = *$nl *1 *2 *3 *4.*$prompt$"		{ pass "$test" }
}

set test transpose-4
send "matrix'\n"
expect {
	-re "ans = *$nl *1 *3$nl *2 *4.*$prompt$"	{ pass "$test" }
}

