#! /bin/sh
for whose in stock fast
do
	for fp in "" -i
	do
		for buf in "" -u
		do
			echo stdiock.$whose $fp $buf:
			if ./stdiock.$whose $fp $buf <<!
a line
!
			then
				: passed
			else
				exit 1		# something amiss
			fi
			echo ''
		done
	done
done
exit 0
