/* sccsdata.c - sccs data file for obj generated by mksccs */

char obj_sccsdata_c_sccsid[] = "@(#)sccsdata.c	1.26 26/7/92";

#include "sccsdata.h"

#ifndef __STDC__
#define const
#endif

/*  Changes since the last version:
 *
 *  dump_object() now returns 0, or the first non-zero return value
 *  from any of the dumpobj callback routines it invokes.
 *  
 *  o_sel.c: Fix boundary condition y coord error in select_field().
 *           Make obj_edit_field() work when there is no window.
 *           Call (*Pre_edit_func)() in obj_edit_field if Pre_edit_func
 *           not NULL.
 *  
 *  fed.c: Make make_edesc() and redraw_string() work when there
 *         is no window.
 */

 const char *_obj_sccsdata[] = {
	"obj version 1.26 (build date: Sun Jul 26 19:59:17 BST 1992)",
	"@{$obj$}: sccsdata.c 1.26 ",
	"@{$obj$}: o_chds.c 1.14 ",
	"@{$obj$}: o_def.c 1.12 ",
	"@{$obj$}: o_disp.c 1.13 ",
	"@{$obj$}: o_globals.c 1.9 ",
	"@{$obj$}: o_lptrs.c 1.11 ",
	"@{$obj$}: o_mkobj.c 1.9 ",
	"@{$obj$}: o_sel.c 1.17 ",
	"@{$obj$}: o_text.c 1.1 ",
	"@{$obj$}: fed.c 1.21 ",
	"@{$obj$}: newtb.c 1.10 ",
	"@{$obj$}: mhole.c 1.12 ",
	"@{$obj$}: fed.h 1.9 ",
	"@{$obj$}: mhole.h 1.2 ",
	"@{$obj$}: newtb.h 1.4 ",
	"@{$obj$}: o_disp.h 1.2 ",
	"@{$obj$}: o_lptrs.h 1.2 ",
	"@{$obj$}: o_mkobj.h 1.4 ",
	"@{$obj$}: o_priv.h 1.6 ",
	"@{$obj$}: o_sel.h 1.4 ",
	"@{$obj$}: obj.h 1.12 ",
	"@{$obj$}: sccsdata.h 1.1 ",
	"@{$obj$}: doc/tech.ms 1.1 ",
	"@{$obj$}: Makefile 1.11 ",
};
