BINDIR='/usr/local/bin'
CC='cc'
CFLAGS='-O'
DEFHASH='english.hash'
DEFLANG='english.aff'
ELISPDIR='/usr/local/lib/emacs/site-lisp'
EMACS='emacs'
LANGUAGES='{english,MASTERDICTS=english.med+,HASHFILES=med+.hash,VARIANTS=american,EXTRADICT=/usr/share/dict/words}'
LIBDIR='/usr/local/lib'
LIBES=''
LINT='lint'
LINTFLAGS=''
MAKE_SORTTMP='-T ${TMPDIR-/usr/tmp}'
MAN1DIR='/usr/local/man/man1'
MAN1EXT='.1'
MAN4DIR='/usr/local/man/man4'
MAN4EXT='.4'
MASTERHASH='med+.hash'
MSGLANG='english'
REGLIB=''
TERMLIB='-ltermcap'
TEXINFODIR='/usr/local/info'
YACC='yacc'
case "$MAKE_SORTTMP" in "")  SORTTMP="-e /!!SORTTMP!!/s/=.*$/=/";; *) SORTTMP=;; esac
