.TH XCDPLAYER 1 "Feb 3 1992" "X Version 11"
.SH NAME
xcdplayer \- X window system interface to run the sun or sgi cdrom drive as a 
typical audio CD player.
.SH SYNOPSIS
.B xcdplayer
[ \fI-toolkitoption ... \fP] [\fI-xcdplayeroption ... \fP] 
.SH DESCRIPTION
\fIXcdplayer\fP is a graphical user interface for controlling the Sun or SGI cdrom
drive under the X Window System.  It provides visual feedback and 
gives the user facilities for mode selection, device control, scanning, and
programming.
.LP
\fIXcdplayer\fP allows previously stored cd title and program information to 
be read from a specified directory and loaded into the player on startup 
or at disc changes.  This directory can be specified either on the command 
line, by using the -cdInfoDir option, by using a customized personal resource 
file, or by setting the environment variable XCDINFODIR.  If no directory is 
specified by any of these methods, xcdplayer looks in the current directory.
.LP
.SH OPTIONS
\fIXcdplayer\fP accepts all of the standard X Toolkit command line options 
(see \fIX\fP(1)), plus the following xcdplayer specific options:
.IP "-debug" 12
Displays debugging messages as the tool runs.
.IP -device devname
CDROM device to use (useful for systems with multiple CDROM drives)
.IP -volBase <[0..255]>
Bottom of volume scale for player [range 0-255] (default 187)
.IP -volPcent <float>
Ratio of volume change [range 0..255] to percent of scrollbar shown 
(default .267).  This value is used in conjunction with the volBase parameter.
.IP -cdInfoDir <path>
Specifies which directory should be used for storing and looking up 
CD information.


.SH SUBWINDOWS
\fIXcdplayer\fP contains the following subwindows:
.IP "Title Window" 20
Displays the title of the CD (if stored or entered) corresponding to the CD
currently in the CD player.  
.IP "Program Window" 
Brought up on press of the program button, this panel contains a viewport
displaying the current selected program, option buttons, and track selection
buttons.  The program window (and program mode) are dismissed via the Cancel
button.
.LP
.SH COMMAND BUTTONS
.LP
.SS "Main Commands"
.IP "\fBplay\fP" 15
Enter play mode.
.IP "\fBpause\fP"
Pause play.  Activating this button has an effect on program selection.
.IP "\fBstop\fP"
Stop disc and reset to beginning.
.IP "\fBprev\fP"
Go back either to the beginning of the previous track (or start of current
track if more than replayThreshold seconds have elapsed); if in program
mode, go to previous selection in program.
.IP "\fBnext\fP"
Go to beginning of next track; if in program mode, go to next program 
selection.
.IP "\fBeject\fP"
Eject the disc. Resets all modes.
.IP "\fBaudio\fP"
Toggle the audio output if possible.  It will default to the best 
quality audio available (SGI only).
.IP "\fBquit\fP"
Exit xcdplayer.  (Leaves disc in last set state.
.IP "\fBcycle\fP"
Cycle the disc.  If in shuffle mode, reshuffle will occur at end of current
shuffle; if in program mode, the program will replay.
.IP "\fBshuffle\fP"
Select all of the tracks in random order.  This button has no effect unless
play mode is not active, and is a toggle to program mode.
.IP "\fBrewind\fP"
Rewind the disc.  If held down, will continue rewinding.  Scan skip amount
and pause interval between skips are controlled by the resources 
scanSkipInterval and scanPauseInterval.  If the disc is paused, it will
skip by the ammount specifed by pauseSkipInterval.
.IP "\fBfast-forward\fP"
Analogous to rewind.
.IP "\fBprogram\fP"
Enter program mode.  If paused, add current track (if not 0) to program.
Brings up program subwindow.
.LP
.SS "Program Commands"
.LP
.IP "\fBSelections\fP" 20
Selections displayed in the viewport of the program subwindow can be clicked 
on, and clicking on the currently selected track deletes it from the program.  
The highlighted selection indicates the current insert/delete point in the 
program, and if the CD is paused, clicking on a selection moves the program 
play point to that selection.  
.sp
.br
Selections can be added to the program either by clicking on
the track buttons on the program form, or by using the forward and previous
buttons on the main form while paused, and then clicking the program button
again.  Pre-insertion before the 1st programmed track is allowed by clicking
on the space preceding the 1st entry.  
.IP "\fBClear\fP"
Clears current program.
.IP "\fBCancel\fP"
Clears current program and cancels program mode and subwindow.
.IP "\fBSave\fP"
Save the current program (if any) and current title to file in cdInfoDir.
This file will then be read whenever the current disc is put into the player.
.IP "\fBtrack buttons\fP"
Add the track number to the program at the current insertion point, or if
active, add track number to the programmable track button.
.IP "\fB+10\fP"
Add ten to the programmable track button.
.IP "\fBprogrammable track\fP"
Add the selected track number (if available on CD) to program at the current
insertion point.
.IP "\fBAll\fP"
Replace the current program with a sequential list of tracks on the CD.
.LP
.SS "Miscellaneous Commands"
.IP "\fBtrack\fP" 20
Show number of tracks on the CD.
.IP "\fBtimer\fP"
Toggle between time elaped and time remaining. If in program mode, and not
paused, toggles to time remaining in program.
.IP "\fBvolume scroll\fP"
Adjust volume of CD player output.
.IP "\fBtitle\fP"
Pop up dialog for editing title display.  Title can then be associated 
permanently with that CD by using the save button in the program subwindow.
The title is displayed on a button in a viewport, so that long titles won't
distort the size of the tool.  

.SH FILES
cdInfoDir/cd.*	these files contain title and stored program info saved for CDs
.SH SEE ALSO
X(1)
.SH LIMITATIONS
Xcdplayer cannot yet read the current volume level and adjust the volume scroll
accordingly, because there is not current support for this in the driver.
.SH BUGS
Xcdplayer occasionally "hangs" on a particular track, never quite reaching
the end of it.  Advancing to the next or previous track, or pressing the
stop button rectifies this condition.
.SH COPYRIGHT
Copyright (C) 1990 Regents of the University of California
.SH AUTHORS
.PP
Rusty Wright
(rusty@belch.berkely.edu)
.br
Will Sadkin
(wsadkin@bbn.com)
.br
Dan Rich
(drich@lerc.nasa.gov)

