include ../Makefile.config

install:
	
	$(INSTALL)  gopherd.conf.5 $(MAN5DIR)
	$(INSTALL)  gopherd.8 $(MAN8DIR)
	$(INSTALL)  gopherindex.8 $(MAN8DIR)
	$(INSTALL)  gopher.1 $(MAN1DIR)
	$(INSTALL)  gophfilt.1 $(MAN1DIR)

clean:
	-rm -f *~
